### ISSUE TITLE
Re-running `task up` is not as smooth as a blue-green deployment should be

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#1019]
Sometimes skafofld [seems to stop streaming logs](https://www.github.com/GoogleContainerTools/skaffold/issues/4633), so I often want to kill the `task up` command and re-run it. In theory this should produce a smooth blue-green deployment where Kubernetes ensures that the old pod isn't disposed of until the new pod is brought up. In practice there is a window where refreshing the page will produce a 502 or a 503 from the ingress controller.

This is low-priority, but at some point I'd like to go look for what's causing this and see if there might be a way to get proper blue-green deployments so that rerunning `task up` never produces 502 or 503 errors.

**Comment by hahn-kev** [comment]
I think we can close this now that we're using tilt
