### ISSUE TITLE
Pull fwdata model version from repo

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1022]
**Describe the feature**
Just like we pull in the writing systems and project id, it would be useful to know the model version.

**Who is this feature for?**
Users of FW lite who might want to sync a project from lexbox

**Pages affected**
Project page maybe.

**Comment by rmunn** [comment]
This one will be easy: any FLEx project will have a `FLExProject.ModelVersion` file at the root of the repo. It's a simple JSON file containing just one property, `modelversion`, e.g.:

```json
{"modelversion": 7000068}
```

I wouldn't put this on the project page as it's highly-technical info and most users won't even know what it means. Maybe in an "Advanced" section that you have to click to reveal.

**Comment by rmunn** [comment]
Note that LfMerge used to handle model versions of 68 or higher, but it now handles only version 72 (technically 7000072) or higher (which is the current model version as of FLEx 9.0). So anything with model version 68, 69, or 70 is FLEx 8.x (model version 71 was never released). LfMerge never supported model versions earlier than 68.

**Comment by rmunn** [comment]
LfMerge would probably benefit from a LexBox API that exposes the model number of a project (see https://github.com/sillsdev/LfMerge/issues/343 for details). So this is worth doing so that LfMerge can improve its behavior.

**Comment by rmunn** [comment]
**Update:** Decided today that frontend should present this as a FW version, e.g. 8.2 or 8.3 or 9.x. Will keep a haradcoded mapping on frontend, updating it on the rare occasion that FW adds a new model version.
