### ISSUE TITLE
Reproducible race condition in creating Mercurial project and uploading .zip file

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#1025]
**Describe the bug**
While working on https://github.com/sillsdev/LfMerge/pull/342, I found a consistent reproduction for the race condition that https://github.com/sillsdev/languageforge-lexbox/issues/765 was addressing. I believe that the fix for https://github.com/sillsdev/languageforge-lexbox/issues/765 did manage to fix the NFS issue for most cases, but https://github.com/sillsdev/LfMerge/pull/342 has a *consistently reproducible* test failure that shows that the NFS issue may not be completely gone.

**To Reproduce**
1. Clone https://github.com/sillsdev/LfMerge/ and check out commit [238049a25025aceb74e78138927477fe4a2d5e08](https://github.com/sillsdev/LfMerge/pull/342/commits/238049a25025aceb74e78138927477fe4a2d5e08).
2. Make sure LexBox is running on localhost.
3. Run `dotnet test -l "console;verbosity=normal" --filter=Foo_`
4. `TusException : The remote server returned an error: (500) Internal Server Error.`
5. Check the LexBox logs and you'll see that `ProjectService.FinishReset` is calling `UpdateProjectMeta` which in turn calls `HgService.GetLastCommitTimeFromHg`, and Mercurial is returning a 404 for `/hg/s/{projectCode}/log?style=json-lex&rev=tip`.

**Expected behavior**
FinishReset would get a correct last commit time and would not return a 404 for a project that exists and has just had a .zip file uploaded to it.

**Comment by rmunn** [comment]
Further test results: if, instead of getting the last commit date from `hg/s/{projectCode}/log?style=json-lex&rev=tip`, we instead get it from the command runner running `hg log -r tip -T {date|hgdate}` then the race condition does not happen. (Consistently, just as it consistently *does* happen if the last commit is obtained via HTTP).

**Comment by rmunn** [comment]
It's definitely the `refreshinterval` causing this. When I set `refreshinterval` to 0 ("always refresh") in hgweb.hgrc and make no other changes, the repro stops reproing. Set `refreshinterval` back to 5 and it fails. (In fact, even a refresh interval of 1 second fails, because of how the tests are arranged: one test looks up `hg/s/{projectCode}/log`, which causes Mercurial to refresh its repo list. Then the next test created a project followed by looking up `hg/f/{otherCode}/log`, but Mercurial doesn't refresh the repo list so it doesn't find the project).

The reason why using the command runner to get the last commit date fixes the issue is because the command runner is using the `hg` command line, and the refresh interval is specific to hgweb.

**Comment by hahn-kev** [comment]
I would be in favor of switching how we get the latest date to use the command runner. We need to be carful and make sure it returns the same date that our current method gets (maybe do both and compare, throw an error if they are off by more than 1 second, then test it against a bunch of repos.

Also, that log just shows that the command returned a 200, does it actually have data? it won't necessarily error if there's no data in the folder.

**Comment by rmunn** [comment]
The `lexentrycount` returned 5 bytes, 4 bytes for "1462" and one byte for the newline. It would have returned "0\n" (2 bytes) if the repo had been empty.

I'll open a PR changing GetLastCommitDate to use the command runner.

**Comment by rmunn** [comment]
Okay, #1026 opened with a fix and a unit test. The dates in the test were taken from an actual repo and have positive, negative, and zero timezone offsets. I've also verified that the code doesn't fall over when run on a repo with no commits in it.

**Comment by rmunn** [comment]
Bumping size estimate up from Small to Medium because this issue has expanded to include figuring out why the GHA integration tests have failures that aren't showing up when I run them locally.
