### ISSUE TITLE
Add a probe to the resumable container to detect when it's stuck and restart it

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1064]
**Describe the bug**
Big uploads can get stuck in the resumable server causing it to stop responding to requests 

**Expected behavior**
K8s should detect that the container is not responding to requests and restart the container/pod.

**Comment by rmunn** [comment]
Currently all access to the resumable API requires authentication. We will want to make the `/api/v03/isAvailable` endpoint available anonymously to make Kubernetes liveness probes easier; as far as I can tell there's no way to get values from secrets into the config for a liveness probe, so you can't set up an Authorization: Basic header except by hardcoding the username and password into the k8s file (bad idea, obviously).
