### ISSUE TITLE
list and add member projects when adding a new member

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1096]
**Describe the feature**
when setting up an org for the first time, the manager would like to be able to easily see the members projects and optionally add them to the org.

When a manger is adding a member, we want to show a list of that members projects below in the same dialog, each project will have a checkbox, for each project that is checked will then be added to the org in addition to the member who was invited

**Who is this feature for?**
Org managers

**Pages affected**
Org user list

**Comment by myieye** [comment]
We certainly need some way to assign lots of projects quickly.

I'd say this suggestion would be ok security wise.
Perhaps we hide explicitly Confidential projects unless the Org Manager is also a Site Admin. Or maybe just always to keep the backend simpler.

- [ ] Speaking of which, we should probably start a campaign to ask people to set the confidentiality of their projects. 🤔
