### ISSUE TITLE
Project page has white text on white background

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#111]
If your browser light/dark theme is set to "auto", the project page (http://localhost:5173/project/sena-3) has the project name, code, and last commit date in white text on the white background. Switch to a dark theme and the page loads with white text on a dark background.

![light-and-dark](https://github.com/sillsdev/languageforge-lexbox/assets/90762/9544dc5a-c05e-4374-9c1c-6de706b25743)

**Comment by myieye** [comment]
I'm pretty sure that's by design. It's for language projects in sensitive areas 🤣.

Jokes aside, nice catch.

**Comment by rmunn** [comment]
@dadukhankevin - Apparently we can assign GitHub issues to anyone who's commented on the issue. So please leave a comment on this issue, and then on https://github.com/sillsdev/languageforge-lexbox/issues/5, so that I can assign it to you and then your face will show up on the issue in our projects board.

**Comment by dadukhankevin** [comment]
Here is a comment (so I can be assigned)
