### ISSUE TITLE
Crdt viewer headword sort puts capitalized headwords first

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#1125]
**Describe the bug**
The list of entries in the Crdt viewer puts capitalized entries/headwords first:
![Image](https://github.com/user-attachments/assets/36172bc3-82dc-4575-9aca-3563053644f0)

**Expected behavior**
Entries like "Ja" and "Jorge" should be sorted amongst the lowercase 'j's.

**Relevant code**

Sorting:
```
queryable = queryable
            .OrderBy(e => e.Headword(sortWs.Value))
```

Headword:
```
    [ExpressionMethod(nameof(HeadwordExpression))]
    public string Headword(WritingSystemId ws)
    {
        var word = CitationForm[ws];
        if (string.IsNullOrEmpty(word)) word = LexemeForm[ws];
        return word.Trim();
    }

    protected static Expression<Func<Entry, WritingSystemId, string?>> HeadwordExpression() =>
        (e, ws) => (string.IsNullOrEmpty(Json.Value(e.CitationForm, ms => ms[ws]))
            ? Json.Value(e.LexemeForm, ms => ms[ws])
            : Json.Value(e.CitationForm, ms => ms[ws]))!.Trim();
```

Adding `ToLower()` to the end of the HeadwordExpression fixes the sorting. I'm just not sure what the most elegant way to provide both lower case and "actual case" options.

**Comment by rmunn** [comment]
Sorting is tricky. Many languages have a sort order that's different than the ordering of Unicode codepoints; for example, in Lithuanian, the correct sort is I - Į - Y - J - K. Probably best to use ICU, or if we're doing LINQ queries, make sure that the thing running the query (Postgres database?) has proper support for ICU collations and knows what the sorting rules are for the language you're looking at.

For a demo, a basic case-insensitive sort is probably good enough, though. But we're certainly going to need to deal with custom collations at some point.

**Comment by rmunn** [comment]
https://unicode-org.github.io/icu/userguide/collation/ has lots more examples.

**Comment by myieye** [comment]
You're right! This is a collation problem, not a case problem 👍

**Comment by hahn-kev** [comment]
It looks like there's an ICU extension for SQLite, I'm not sure we'll be able to use it everywhere. But it's worth checking out. I'm not sure how this works with ignoring cases but it's worth checking out 
https://www.sqlite.org/src/doc/trunk/ext/icu/README.txt
