### ISSUE TITLE
JWT refresh middleware is buggy and out of date

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#1180]
**Describe the bug**
The middleware for detecting when to refresh JWT tokens is buggy and out of date.
- For projects: it refreshes too often, because the assumption that a user will only see projects they're a member of no longer holds due to non-confidential projects
- For orgs: it will essentially refresh precisely every time a user goes to the org list (which almost sounds like a good idea, but is certainly not the intention)

As a result:
- Visiting an org with non-confidential projects that the current user is not a member of will always refresh the token
- Unless the above is true ☝, the token will never be refreshed on an org page even if the user is added/removed from the org or their role is changed

**Expected behavior**
Our middleware should detect (whenever possible) actual permission changes and refresh the token accordingly.

**Comment by hahn-kev** [comment]
is this fixed now that #1199  is merged

**Comment by myieye** [comment]
@hahn-kev No the fix is coming in #1218
