### ISSUE TITLE
implement new update api for writing systems

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1189]
reference the update implementation for UpdateEntry

**Comment by rmunn** [comment]
While creating UpdateWritingSystemProxy, I discovered that MiniLcm writing systems have a Font property that's a single string, but LCM writing systems have a Fonts property that's a dict keyed by string. We'll need to decide on how to handle that model mismatch during updates.

**Comment by hahn-kev** [comment]
The font in the miniLcm version of the Writing system is the default writing system, so maybe a change should just change the default font. I'm not even sure how we would use more than one font, I might need to get info from Jason about it.
