### ISSUE TITLE
returnTo in invite links is absolute

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#1226]
This is in prod.

**Describe the bug**
The returnTo url query-param values in Invite links should be relative, but a recent change made them absolute.

We had a similar situation previously, but then it was using localhost as the domain. That's not the case now, so the invite workflow seems to be working fine. But, I think this is still worth changing.

**To Reproduce**
1. As an admin invite a user (that doesn't have an account) to a [test project](https://lexbox.org/project/testlangproj-ih-flex?id=51681b00-fa83-47e3-88bb-c2e9e790f46a). (e.g. by [generating](https://www.developermail.com/mail/) a developermail email address).
2. Look at the returnTo query-param value in the invite link. It starts with https.

**Expected behavior**
returnTo should be relative.

**Comment by hahn-kev** [comment]
this is really weird I thought we fixed this recently
