### ISSUE TITLE
Login with password

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#13]
Users should be able to login with a username or email and a password.
Mockup: https://whimsical.com/log-in-5yUaDus25m5BW2SZ3qLhUC

**Comment by hahn-kev** [comment]
I would love it if we could hash the password on the frontend before we send it to the backend. I've done a test and using the web crypto apis and we can do the pre salt hash before we send it to the server.

**Comment by longrunningprocess** [comment]
yeah, we can definitely do that, I'd be interested in talking it out a bit first

**Comment by longrunningprocess** [comment]
I couldn't recall where we left things when we discussed the fact that the backend will not be able to enforce any validation logic such as empty fields or min-length constraints... I'm going to hold off on this until

**Comment by hahn-kev** [comment]
I'm not sure what you mean that we can't do validation on the backend. We will still do that, we just can't validate password rules. But we will totally validate if fields are empty or null. However they'll be handled on the front end first so you don't need to worry about it.

**Comment by hahn-kev** [comment]
Here's the test of password hashing in the frontend. If we want this test to stick around it should probably be refactored into the right place but this shows that it works.
https://github.com/sillsdev/languageforge-lexbox/blob/develop/frontend/src/index.test.ts#L10
