### ISSUE TITLE
Verify email address when user changes it

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#156]
Related to [verifying a user's email when the register](https://github.com/sillsdev/languageforge-lexbox/issues/47). And [completes users being able to update their settings](https://github.com/sillsdev/languageforge-lexbox/issues/5).

We may need to temporarily store both their old and new email addresses.

**Comment by hahn-kev** [comment]
Let's put this in v1 and just don't let users change their email until it's implemented.
