### ISSUE TITLE
failed login shows a popup error and the login button is disabled and still spinning

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#164]

**Comment by myieye** [comment]
Fixed by
https://github.com/sillsdev/languageforge-lexbox/commit/da02d5f93cde12e476e00264f0586d49ed737b12
and
https://github.com/sillsdev/languageforge-lexbox/commit/6d15c844f3efacca97f1bb87465e0db35c8804a3
