### ISSUE TITLE
Error when trying to change project member role

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#167]
1. Open a project
2. Click a user
3. click 'Change Role'
4. error:

![Image](https://user-images.githubusercontent.com/4575355/251087059-fead1a01-6eee-4d00-aca3-a50d06d04b6f.png)

**Comment by myieye** [comment]
We have quite a few TS compile errors in our repo. I think they mostly came when we dropped Hasura.
The real problem here is that we don't have any checks in place. We should be running `svelte-check` in CI.

**Comment by myieye** [comment]
Fixed in https://github.com/sillsdev/languageforge-lexbox/commit/830fe726df0e136e93212fc06d829c755622a34b
