### ISSUE TITLE
Error clicking Delete account after email verification

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#195]
Trace here: https://ui.honeycomb.io/sil-language-forge/environments/staging/datasets/lexbox-sveltekit-client/result/JAFEwJymg1T/trace/EAdrnctZ6uK?fields[]=c_name&fields[]=c_service.name&span=ce6336b18a911e0e

**Comment by myieye** [comment]
All sorts of wonky things happen when you navigate to the app via an email verification link 🤔


![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/179729c4-04f9-40cc-8b66-1eb310f9cdfe)
