### ISSUE TITLE
Account Registration

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#2]
Users need to be able to register an account. 

- Captcha required
- Name
- Email
  - Verify Email
- Password
  - Enforce password strength.

Open questions:

- [ ] what are the password rules?
- [ ] what restrictions should there be for accounts that we don't trust?

Things to implement:
- [x] Registration API
- [x] Captcha backend support?
- [ ] Front end UI

**Comment by longrunningprocess** [comment]
# Mockup

https://whimsical.com/register-new-account-QX1wYsb9nQGWoWxcKeWRpK

**Comment by hahn-kev** [comment]
API Implemented. 
url: `/api/User/registerAccount`
body:
```json
{
  "name": "Test",
  "email": "test@test.com",
  "passwordHash": "5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8",
  "turnstileToken": "test"
}
```

Turnstile is setup, in dev it'll use a test token that always passes, you just need to pass something in. There's some [other test tokens](https://developers.cloudflare.com/turnstile/frequently-asked-questions/#are-there-sitekeys-and-secret-keys-that-can-be-used-for-testing) you can use to test a bad response. There will also be an error if trying to reuse the same email.

This is what an error response looks like:
```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-7bd7662edfe8b4e6e0234ae9fe76d4da-d5f7efbe92147b70-00",
  "errors": {
    "Email": [
      "email already in use"
    ]
  }
}
```

If there's no errors then a good response should look exactly like the user from the login api. Also the user will be logged in.
