### ISSUE TITLE
One set of quote marks needed in docker-compose.yaml

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#20]
On a brand-new cloned repo, running `docker-compose up -d` fails with:

> "ERROR: The Compose file './docker-compose.yaml' is invalid because:
> `services.hg.environment.HGK_DISABLE_SSH` contains true, which is an invalid type, it should be a string, number, or a null

To fix it just involves putting the word `true` in quotes so that it YAML will consider it a string. I don't have write access to this repo yet, and I don't feel like cloning the repo for a one-line change, so here's the patch to fix it:

```diff
diff --git a/docker-compose.yaml b/docker-compose.yaml
index b1731c7..74550cd 100644
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -81,7 +81,7 @@
 #      the path must be hardcoded in local.hgrc, check the note there for more info
       HGK_REPOS_PATH: /repos
       HGK_ADMIN_USERNAME: admin
-      HGK_DISABLE_SSH: true
+      HGK_DISABLE_SSH: "true"
       HGK_ADMIN_PUBKEY: /admin-pubkey
 #      setup is only required the first time, it'll error if it's already been run but that's fine.
     command: bash -c "hgkeeper setup ; hgkeeper serve"
```

**Comment by hahn-kev** [comment]
huh, that's really weird. Neither I or Billy have seen that. I'll go ahead and fix it, thanks for checking this out Robin.

**Comment by rmunn** [comment]
I probably have an older version of docker-compose; perhaps newer versions default to strings even for values like "true". My docker-compose version is 1.29.2.
