### ISSUE TITLE
password field gets autofilled on edit user page (for admin)

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#201]
we can probably just change the ID of the field to fix this, but we should test a couple different password managers to see what they do.

this could cause an admin to accidentally change the users password.

I also just accidentally changed the Test editor account to use my email, I suspect it's because of this.

**Comment by myieye** [comment]
I think this is generally fixed with https://github.com/sillsdev/languageforge-lexbox/commit/4070c005bc0a9cae47fe38e41effabd4aa657083 and https://github.com/sillsdev/languageforge-lexbox/commit/54a0ec06684fa4d09f5e04fc4ecf4f69ab215895.

I'll still test it in staging on Chrome, Edge and Firefox with their default password managers / autofill capabilities.

**Comment by myieye** [comment]
@hahn-kev I think it's working well now. Perhaps you'd like to try it on your machine, because you experienced the problem.

**Comment by hahn-kev** [comment]
It looks good for password, but it's still nagging me about the email, and if I blank out the email field it'll prompt me to use a saved address and then it'll autofill the password with my password.

I just played with it for a while. Firefox will try to fill in the email if any of these are true (and it ignores autocomplete=off)
- label = email
- id = email
- type = email

having any of those in place means that FF will try to fill in your email address there if it's empty (and there's an annoying pop up as seen below no mater what, notice that it's not even in the right place because of the animation for the dialog moved the input 😔). 
![image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/88b753ca-d80c-4a7d-9b01-279c3801f480)

anyway... I don't want to change the input type to text as it's helpful for users on a phone, so I don't see a nice way to fix this. There's a bunch of other hacks I've seen (like created up to 3 hidden fields to trick pw managers to use that instead of the real one, but that just seems like an arms race), but I don't really care enough, especially since this is an admin feature.
