### ISSUE TITLE
adding project members does not update the UI

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#202]
when a project member is added the list does not update in the UI without a refresh. Same with removing a user

**Comment by hahn-kev** [comment]
right now this is difficult to fix cleanly because we can't select out what we want from the db when executing a mutation. That's due to this bug in hot chocolate https://github.com/ChilliCream/graphql-platform/issues/5300

**Comment by hahn-kev** [comment]
I ended up working around the above issue by always selecting the data we need in this use case, instead of dynamically based on the gql fields selected

**Comment by myieye** [comment]
🧪
