### ISSUE TITLE
dry run data migration from legacy to new system

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#207]
Steps that need to happen for migration from redmine to lexbox

1. change dns for domain names to lexbox prod in maintenance mode
2. take a dump of the redmine db and import into a local mysql db
3. execute `/api/migrate/migrateData` in swagger with an instance connected to that local mysql db.
4. export local postgres db
5. import dump to prod postgres db
6. copy repos from redmine to lexbox (need some help on the best way to do this)
7. take lexbox prod out of maintenance mode

can be done later:
1. execute `/api/project/updateAllRepoCommitDates` api. Might take a while and need tweaking
2. execute `/api/project/autoUpdateUnknownProjectTypes` tracked in #199 

things to figure out
- [x] how exactly the transfer repos from redmine to lexbox
- [ ] #223

**Comment by hahn-kev** [comment]
new plan

- migrate all sql data at once
- proxy s&r traffic to redmine, use the secret key that LF Merge is using for auth to redmine
- migrate repo data one at a time from redmine to avoid data corruption issues
- in case of proxy issues we can rollback DNS changes

**Comment by hahn-kev** [comment]
Need to determine specifically how we're going to migrate data. Do we use SSH? or pull the data out via a hg clone? or something else I'm not sure. I'd like this to happen automatically at the push of a button, not a manual task that a dev has to do.

**Comment by rmunn** [comment]
Recommended rsync options: `-vaxHAXP`

- `-v` is "verbose" and lets you see the file currently in process in rsync's stdout
- `-a` is "archive" and basically enables a bunch of other flags that say "copy permissions, modified dates, descend recursively, copy symlinks as syminks"
- `-x` is "one file system" and says "don't cross filesystem boundaries" (in case there's a mount point underneath what you're copying)
- `-H` is "hard links" and preserves hard links (in addition to the symlinks included in `-a`)
- `-A` is "ACLs", so if the source filesystem used Access Control Lists, those will be saved
- `-X` is "xattrs" and preserves extended attributes (used for file metadata and other things)
- `-P` is "show progress and keep partial files": it shows a progress indicator during file transfer (so you can see how much time remains on that one file) and if the transfer is interrupted partway through, the partially-transferred file is kept. This will allow the *next* rsync to resume from the point where the transfer was interrupted, and eventually finish even in a flaky network environment.

If you don't need verbosity, `-v` can be dropped and `-P` can be replaced with `--partial`, which keeps partial files but doesn't show progress.

An optional `-z` can be added to compress files before transfer, which saves bandwidth at the expense of more CPU usage. In an AWS-to-AWS environment, we'd want to leave `-z` off.

**Comment by hahn-kev** [comment]
migration was a success! This looks like a good plan at the moment.
