### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#21]
We would like to support localization from the start. We don't need to support any other languages yet, but we want it accounted for so we don't make this too difficult in the future. This may or may not be MVP it depends on how important it is to include from the start.

**Comment by hahn-kev** [comment]
@longrunningprocess can you look into this one?

**Comment by longrunningprocess** [comment]
see what you think so far:  [i18n](https://github.com/sillsdev/languageforge-lexbox/commit/659aff334b2d26e6473c2b08424e76fabad46c5d)

**Comment by hahn-kev** [comment]
closded by #24
