### ISSUE TITLE
Rework some navigation aspects

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#219]
Something like this:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/aa162491-c070-438a-bfd4-0b67ba244cfb)

See: https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1691050692961389

@hahn-kev:
> I like it either in the breadcrumb bar on the right, or in the title bar. But then it feels very confused with the current menu icon. Maybe that should just be a hamburger icon?

If we put it in the title bar, I think we should remove the extra user-button and/or change the current side-bar opener to a hamburger icon.

Also, these buttons should only be on bigger screens. Mobile users just get the side bar.

**Comment by hahn-kev** [comment]
We should also consider where to put a language picker button

**Comment by hahn-kev** [comment]
- [ ] don't close sidebar if blank space is clicked
- [ ] change "My Projects" bread crumb to "Home" (maybe with an icon, make it look more clickable)
- [ ] add username to User Icon
- [ ] prefix Register Icon with "Register"
