### ISSUE TITLE
UI moving when toggling show deleted

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#237]
As seen here:

![Image](https://user-images.githubusercontent.com/4575355/260400276-c4bf9fe8-1ebb-42aa-a5bd-ca2c90884f25.gif)

is this just because the code column gets wider?

Feel free to close if you're ok with this Tim.

**Comment by myieye** [comment]
Fixed in https://github.com/sillsdev/languageforge-lexbox/commit/d1c232f029b6abef2576b499092346bd00ecbedf
Now the tables just always fill the width.
