### ISSUE TITLE
invite users to join LD when invited as a project member

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#239]
right when a user adds a project member, if there's no user matching that email address then nothing happens. We would like to send that user an email so they can create an account.

**Comment by hahn-kev** [comment]
we don't want to store any PII in our database before the user has signed up. To achieve that we will create a jwt with the signup details, including the project that the user should be added too once they have signed up an account. This is secure because we validate the jwt was signed by us.

**Comment by rmunn** [comment]
After discussion with Kevin, we'll reuse the VerifyEmail endpoint from LoginController. The email we generate will link to the verification URL, and we'll just tweak VerifyEmail so that if `user == null`, instead of returning 404, we create the user.
