### ISSUE TITLE
Record project sensitivity when project is created

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#254]
Just have a check box for if the project is sensitive. Description: "Protects language projects that are at risk"

optionally show a banner recommending users use an alias for the project name.

- [ ] add column and data
- [ ] migrate existing data (out of scope of this issue)

related to #578

The Paratext registry has a similar feature, take a look at their message in the UI

**Comment by hahn-kev** [comment]
Here's what the paratext registry does for this. You can read about it in the [help docs](https://paratext.org/paratext-help-and-support/registry-training-and-help/registry-management/registration-reviewer-guide/) also.
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/6a676f63-4cb9-4241-a9ee-cb1280d27bb7)

I don't think we need test or training because that's covered in the retention policy. So a checkbox might be better suited, and we can include some similar warnings, I also like the idea of requesting a review for sensitive projects. But that's way down the road. For now we just want to design a UI to record this.

With the DB design we need to keep in mind that all our existing data needs to default to unknown for sensitive projects. We do not want to default to either public or sensitive as we're unsure.

**Comment by myieye** [comment]
The docs linked above are for registry managers.

Here are the [docs for normal users](https://paratext.org/paratext-training/tutorials/create-and-register-a-new-project/) that want to register a project.

They include a link to the [additional steps](https://paratext.org/support/registry/confidential-projects/) link seen in the screenshots.
