### ISSUE TITLE
Indicate that special characters in passwords could cause trouble.

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#255]
Because usernames and passwords are not necessarily url-encoded by Chorus, users should avoid using special characters and we should tell them that and probably just restrict passwords to `([a-Z][0-9]-)+`.

E.g. I noticed that
- For project-lookup the password `test-temp-0:?"!$` worked, but the `&` character didn't.
- Send/Receive didn't work with the password: `test-temp-0:?"!$`. I'm not sure what the culprit is exactly
- `test-temp` is fine for both.

**Comment by hahn-kev** [comment]
@rmunn would you determine what characters cause problems so we can inform users what not to use in their password.

**Comment by rmunn** [comment]
https://github.com/sillsdev/chorus/issues/324

Three characters cause problems: `&` (always), `+` (always), and `%` (if followed by two alphanumerics that look like a hex code, which happens often enough that it will cause problems and should be warned about). Every other punctuation character, as well as space characters and non-Roman scripts, worked. So we only need to scan for the three characters `+&%` and we'll be able to warn people whose passwords might not work.

**Comment by myieye** [comment]
We need to revisit this. Apparently a user recently couldn't log in, because they had a `:` in their password.
