### ISSUE TITLE
New LexBox users can't S/R

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#256]
@hahn-kev I'm creating this so I don't forget, but perhaps you've already thought it through....

Chorus looks up available projects for a user and does S/R using their username and password. The username is not URL encoded.
New LexBox users don't have a username, they only have an e-mail address, which we can't use as their Chorus S/R username, because Chorus doesn't URL-encode the username.

How do we let new LexBox users user Chorus? Do we improve Chorus as part of MVP and require new users to have a current FLEx/Chorus version?

**Comment by hahn-kev** [comment]
Actually we can use emails to login from Chorus, we just weren't looking up the user by email on the backend. Fixed in b8c9ad2f8e09b22f1b15f470d80a84f9e7245454
