### ISSUE TITLE
update last commit date for resumable protocol push

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#261]
when a normal hg command pushes data we update the last commit date, we should also do that for resumable, though we'd have to detect when that is as right now I'm not sure.

**Comment by rmunn** [comment]
Looking through the hgresume code, it looks like we want to look for the `finishPushBundle` command being sent to Resumable. Specifically, the URL would look like `https://hostname.example.com/api/v03/finishPushBundle?query=params`. Then we can run the RefreshProjectLastChange method similarly to how OnHgRequest does it.

If we want to detect pulls, even if they didn't change the project, then we'd look for `finishPullBundle` in the URL instead.

**Comment by hahn-kev** [comment]
FYI this is the [helper method](https://github.com/sillsdev/languageforge-lexbox/blob/98c3b2e965c9fdd33787d523659989404eae8695/backend/SyncReverseProxy/HgHelpers.cs) you want to get the project code during a resumable request
