### ISSUE TITLE
Give project managers permission to create projects

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#263]
Only allow users that are or have been a project manager to create new projects.

## Why?
This gives LexBox the same amount of user privacy/security as LD:
- In LD project managers are able to search the entire user list
- In LexBox project managers can (sort of) do that by checking if accounts exist by trying to add them by email address

If a user is a project manager it means someone has vetted them to some extent. Instead of any random user being able to sign up and start creating projects (what we currently have) a user now needs to earn trust by either (1) requesting a project to be created by an admin (same as LD) or (2) having another user promote them to an admin.

## Implementation
- DB flag/permission (readonly even for admins, because it could automatically get set to true any time i.e. when the user becomes a manager on aother project). Having a flag/additional permission prevents the user from losing it if they stop being a PM.
- All current project managers are given the permission at migration time.
- Whenever a user becomes a project manager they gain the permission.

**Comment by myieye** [comment]
They're both pretty hard to explain. What would be easier to explain is an additional system role between admin and user.
