### ISSUE TITLE
Cleanup .zip and reset folders from after project reset

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#275]
Right now devs need to manually cleanup both .zip files and the reset folders that end up in _____deleted_____, we'd like to automate this away so it's automatic.

- [ ] delete zip files used to let end user download project
- [ ] delete folders moved for a reset

**Comment by rmunn** [comment]
The .zip files are being created in the system temp dir, so it's probably okay to let a server process handle it, deleting any files older than 7 days. The folders being moved for a reset are using the HgService.SoftDeleteRepo method, so once we have a policy in place for handling soft-deleted projects then that will affect this as well. Perhaps soft-deleted projects get hard-deleted after 90 days?
