### ISSUE TITLE
Research making LibLCM stateless

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#28]
LibLCM currently loads the entire fwdata file into memory when it loads a project.
That's not how the web works. So if we want to wrap LibLCM behind a web API, we need to make it stateless and only load objects on demand as needed.

In this issue we want to get a feel for what that would involve.

**Comment by myieye** [comment]
# Current progress

### The state of "fluffing up"

LibLCM ist accessed by initializing an `LcmCache`.
When the cache is initialized "surrogates" are created for the data objects. (`CmObjectSurrogate`)
These surrogates are then "fluffed up" when they are accessed the first time.
A select few (~10) are "fluffed up" during the initialisation process.
Surrogates can be explicitly fluffed up in bulk by using `IDataSetup.LoadDomain[Async](BackendBulkLoadDomain.(All|None|Lexicon|Scripture|...))`.
This is how FLEx [appears to](https://github.com/sillsdev/FieldWorks/blob/32068b620546475ad25ff73c5dcb8442322c13ca/Src/LexText/LexTextDll/LexTextApp.cs#L783) initialize the entire model when a project is loaded.

- [x] So, we've apparently accomplished turning off fluffing everything immediately. 👍

### What gets fluffed up during initialization

This:
```
Loading: LangProject (c1ed6dba-e382-11de-8a39-0800200c9a66)
Loading: LangProject (c1ed6dba-e382-11de-8a39-0800200c9a66)
Loading: Scripture (a7fb3b66-beff-4199-abba-fdbdb0bbbf85)
Loading: Scripture (a7fb3b66-beff-4199-abba-fdbdb0bbbf85)
Loading: CmResource (09756a52-af7b-40a4-83d9-cd82431cc701)
Loading: CmResource (2d220733-d886-4333-a691-5f00b44612f5)
Loading: CmResource (3c7c17ca-c956-441d-a1d9-c0592dd1973f)
Loading: CmResource (41b4d47d-160c-4558-a42c-3a530e749885)
Loading: CmResource (4b6e326a-c33a-43d2-93f2-3415f1f5a54c)
Loading: CmResource (5494c660-8f7f-4324-a786-fc874701b4fa)
Loading: CmResource (6c0355f9-6b37-4161-958a-de4b17bac844)
Loading: CmResource (b56babcc-1ce1-4160-a77f-d8ead4a0e3af)
Loading: CmResource (b95863a6-47ef-48e7-b977-8b3c0643db21)
Loading: CmResource (ef7754c1-80ee-4fd1-aced-0bb5baa912a8)
Loading: CmResource (facd245e-82ca-4953-bae1-5bcc573b6833)
```

### So how long does it take to initialize the cache

Here's where (99.9%) of the time gets spent when loading Sena 3...

The first time takes ~2.5s:
```
           82ms [LcmCache.CreateCacheInternal => CreateCacheInternal]
           69ms [CreateCacheInternal => GetInstance<IDataSetup>()]
           35ms [XMLBackendProvider.LockProject]
          817ms [XMLBackendProvider.ReadInSurrogates - MakeSurrogates]
         1353ms [BackendProvider.InitializeWritingSystemManager => new CoreLdmlInFolderWritingSystemRepository]
           33ms [BackendProvider.BootstrapExtantSystem]
                4ms [ServiceLocator.WritingSystems.DefaultAnalysisWritingSystem]
                       12ms [EnsureBtForScrParas]
                   14ms [DataStoreInitializationServices.PrepareCache()] (Missing: 2ms)
               17ms [NonUndoableUnitOfWorkHelper.Do] (Missing: 3ms)
           21ms [LcmCache.Initialize()]
     2427ms [LcmCache.CreateCacheFromExistingData] (Missing: 17ms)
 2428ms [Load cache] (Missing: 1ms)
```

Consecutive loads are significantly faster. Apparently there's a significant amount of work that gets cached in memory:
```
            3ms [LcmCache.CreateCacheInternal => CreateCacheInternal]
           10ms [CreateCacheInternal => GetInstance<IDataSetup>()]
            0ms [XMLBackendProvider.LockProject]
          661ms [XMLBackendProvider.ReadInSurrogates - MakeSurrogates]
           98ms [BackendProvider.InitializeWritingSystemManager => new CoreLdmlInFolderWritingSystemRepository]
            9ms [BackendProvider.BootstrapExtantSystem]
                2ms [ServiceLocator.WritingSystems.DefaultAnalysisWritingSystem]
                        6ms [EnsureBtForScrParas]
                    6ms [DataStoreInitializationServices.PrepareCache()]
                6ms [NonUndoableUnitOfWorkHelper.Do]
            8ms [LcmCache.Initialize()]
      795ms [LcmCache.CreateCacheFromExistingData] (Missing: 6ms)
  795ms [Load data 2]
```
Here we see that ~75% of the time is spent making the surrogates.

**Comment by hahn-kev** [comment]
Nice work! Just curious for `LangProject` and `Scripture` it looks like the same one is getting loaded twice, is that a logging bug or are they actually being loaded twice?

Also I like the timeline, what did you use to make that?

**Comment by myieye** [comment]
Just a custom util. I threw it in a gist: https://gist.github.com/myieye/133693eeef6b90367b40b7a640fb77fb

**Comment by jasonleenaylor** [comment]
I think that a server based LCM would need to have a different implementation of WritingSystemManager, or at least CoreLdmlInFolderWritingSystemRepository. There is a concept of a local and global writing system store, the writing system information is contained in .ldml files which is an xml format.
These files are retrieved from a web api, https://ldml.api.sil.org/ to make sure that we are getting the latest data when we create a project.
The 'global' store was intended to allow different projects and applications on the same machine share the same writing system definitions with the local store being specific to a project. Synchronization of those stores was handled on cache initialization I think.
On a server hosting many projects we would probably want to store the writing system information in a database. We might consider a separate service outside of LCM responsible for keeping that data up to with the latest versions available from the API. 
Writing system data is mission critical information, but it is maintained separately from a LangProject and referenced only by a writing system identifier. This is another piece of going stateless which we will need to address which I didn't initially think about. There will be a need for projects to have overrides to the global data because two different projects could be working with the same language and making different choices. (writing systems include what characters are in a language, numbering systems, sorting rules, ect.)

**Comment by myieye** [comment]
@Jason N thanks for those insights!
So, making live writing system information an inconsequential query away from LibLCM-Cloud is something we'll need to figure out at some point.
It's also nice to know about writing-system overrides. I was wondering how that worked when I played around with configuring characters in FLEx.

Note to self: LDML = Unicode Locale Data Markup Language

**Comment by myieye** [comment]
## My journey

I've implemented "stateless spike" in [LibLCM](https://github.com/myieye/liblcm/tree/efcore), based on my [EFCore backend](https://github.com/myieye/liblcm-efcore).
More effort than I anticipated went into mapping objects back and forth between EFCore types and LibLCM types. It's not obvious to me if we'll end up doing something like that.

Here's what the performance of loading the cache looks like. The only cost involved is now the writing-system initialization:
```
  174ms [Load cache]
      174ms [LcmCache.CreateCacheFromExistingData()] (Missing: 2ms)
           12ms [LcmCache.CreateCacheInternal: CreateCacheInternal()]
            0ms [LcmCache.CreateCacheInternal: GetInstance<IDataSetup>()]
                0ms [CmToEFCoreAutoMapperConfig.InitMapper()]
           98ms [BackendProvider.InitializeWritingSystemManager: new CoreLdmlInFolderWritingSystemRepository()]
           62ms [LcmCache.Initialize()]
               62ms [LcmCache.Initialize: Read: ServiceLocator.WritingSystems.DefaultAnalysisWritingSystem]
                0ms [LcmCache.Initialize: NonUndoableUnitOfWorkHelper.Do()]
                    0ms [LcmCache.Initialize: DataStoreInitializationServices.PrepareCache()]
                        0ms [DataStoreInitializationServices.EnsureBtForScrParas()]
```

And here's what querying for the LexemeForm "zungunuk" and making and verifying changes to it looks like.

The slow times for finding the lexme via search in LibLCM, just demonstrate that it's doing the query in memory after loading and mapping the whole table.

The writes/saves are fairly zippy, but not necessarily impressive.

```
 1035ms [ReadWriteUndo(LexemeForm.Form)] (Missing: 10ms)
      453ms [AssertValueInLcmAndEF-BySearch(originalValue)] (Missing: 2ms)
          434ms [Find lexeme - LibLCM]
           17ms [Find lexeme - EFCore]
       12ms [set_String(newValue)]
      185ms [Save()]
      171ms [AssertValueInLcmAndEF-BySearch(newValue)] (Missing: 1ms)
          168ms [Find lexeme - LibLCM]
            2ms [Find lexeme - EFCore]
       19ms [AssertValueInLcmAndEF-ById(newValue)] (Missing: 2ms)
           11ms [Find lexeme - LibLCM]
            6ms [Find lexeme - EFCore]
        2ms [Undo()]
        6ms [Save()]
      175ms [AssertValueInLcmAndEF-BySearch(originalValue)] (Missing: 1ms)
          172ms [Find lexeme - LibLCM]
            2ms [Find lexeme - EFCore]
        2ms [AssertValueInLcmAndEF-ById(originalValue)] (Missing: 1ms)
            1ms [Find lexeme - LibLCM]
            0ms [Find lexeme - EFCore]
```

## Stateless learnings

### Backend provider

LibLCM code is familiar with the term BackendProvider (or BEP). BackendProvider is in fact the name of a class, but it's not actually a first-class citizen in the code base, it's a fairly XML-specific (and has been for [a long time](https://github.com/sillsdev/liblcm/commit/70dfa7e4c6134a89d6af25510d549523b07ab655#diff-eb6c015a9701ed583455dc72d6caf0484295ed509a50c35e6d014243b9963e07)) implementation of 3 data interfaces and it's these interfaces that are actually referenced throughout the code base.

### The catalogue problem

You can't query a huge XML document. You need to know what's in it. So even though the current backend doesn't necessarily load the entire data model into memory it does create a **cataloge** of every available object. That means the code can request any object at any time by ID/Guid without needing to specificy the type of the object. That is perhaps the biggest assumption that contradicts a statelss DB backend. A DB needs to know what table to query.

There are currently 2 main ways to request objects:
- All objects of a certain type
- A single object by ID (without type information)

Of course the code generally needs to know what object it's getting in order to use it, so the type information is somewhere. It was even quite trivial to change the core `GetObject(id)` methods to include a type, because the BEP is primarily accessed from typed repositories. However, there are other places in the code that implicitly pass a very generic type (e.g. `ICmObject`) that cannot be translated to a database table. So there's work to do here to consistently provide that type information to the BEP.

This problem is exemplified by...

1. A fairly long list of "well known IDs". E.g.:
```
public partial class LexEntryTypeTags
{
    /// <summary>Unspecified Complex Form item in LexEntry Types list</summary>
    public static readonly Guid kguidLexTypeUnspecifiedComplexForm = new Guid("fec038ed-6a8c-4fa5-bc96-a4f515a98c50");
    /// <summary>Compound item in LexEntry Types list</summary>
    public static readonly Guid kguidLexTypCompound = new Guid("1f6ae209-141a-40db-983c-bee93af0ca3c");
```

2. That `goners` are identified only by their ID:

```
public bool Commit(
    HashSet<ICmObjectOrSurrogate> newbies,
    HashSet<ICmObjectOrSurrogate> dirtballs,
    HashSet<ICmObjectId> goners) <-- these IDs don't contain any type information
```

## Lazy loading

We know that for performance reasons the FLEx team decided to [eagerly load the whole data model](https://github.com/sillsdev/FieldWorks/blob/32068b620546475ad25ff73c5dcb8442322c13ca/Src/LexText/LexTextDll/LexTextApp.cs#L783) at start time. Without this, generated property accessors lazily load their dependencies on demand.

A stateless LibLCM would need to be smarter. E.g. in my example spike I used a LexEntry ID to update the Lexeme's Form. There should only be one round-trip to the DB so the the Lexeme-Form should be eagerly loaded with the Lexeme, not lazily-loaded after the fact. XML/plain text offers no features to efficiently load multiple objects at once. So, of course (I think at least...), there are no preexisting strategies for eagerly loading related entities. (The exception is `IDataSetup.LoadDomain[Async](BackendBulkLoadDomain.(All|None|Lexicon|Scripture|...))`, but that's not the sort of strategic eager loading we're looking for).

## The equality problem

A statefull LibLCM caches everything and thus never creates duplicate objects. Thus it can always compare objects references to determine object equality. An anecdotal example:
When manipulating a `MoForm` it determines if it is the main (and no an alternative) `MoForm` by comparing itself to its owner's lexeme form:  `MoForm.Owner.LexemeFormOA`. If the Owner gets lazily loaded and doesn't hit a cache we'll end up with 2 different objects. They could of course trivially be compared via ID, but they're not, because what's the point in a perfectly cached world.

Of course, within the scope of a single web request we wouldn't want to be querying the same object multiple times, but it still seems uncommon to compare object references to the extent that it's currently being done.

**Comment by hahn-kev** [comment]
That's great work Tim, and thanks for the writeup.

For the equality issue one solution that may work is to override the equals operator for our objects and then just compare the object ID, instead of the instance. This means we wouldn't have to rewrite any code that's doing an equality check.

As for querying that's really good to know. It sounds like we would have to invest in refactoring that code to move the query into the BEP.
It might be possible to avoid this if the code is just using Linq functions as we could replace the current usage with IQueryable and it'll still do the same thing that it currently does. But I would much rather delegate that work to the BEP to provide a better separation of concerns.

**Comment by megahirt** [comment]
@myieye this is really great research and and a solid write-up that explains the current issues you've found so far, including performance and code assumption issues.  Thank you very much!

**Comment by myieye** [comment]
@hahn-kev I updated/corrected my section on querying. 😉
