### ISSUE TITLE
Add loading indicator for when loads take a while

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#283]
What GitHub does is add a div with class `turbo-progress-bar` (suggesting that they use https://github.com/hotwired/turbo) that has `style="width: N%` where the value of N is rapidly changing. (Interestingly, that div is actually inserted *before* the `<body>` element, something I don't suggest we replicate). We'd probably use https://daisyui.com/components/progress/ for the loading-indicator progress bar.

**Comment by hahn-kev** [comment]
Was just using our UI from my phone and the lack of activity indicators left me wondering what was happening from time to time. The top issues was
- after login, while navigating to the admin page, the loading indicator on the login button was off, making it look like the login had failed while the admin page was still loading
- user search hits the server, and is denounced, meaning if you are searching for a user it can be really hard to tell if your search has been executed or not, especially when the search returns no results.
