### ISSUE TITLE
sendBeacon - cannot send

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#307]
We often get `sendBeacon - cannot send` errors [in the browser console (honeycomb)](https://ui.honeycomb.io/sil-language-forge/environments/test?query=%7B%22time_range%22%3A5184000%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22exception.message%22%2C%22op%22%3A%22contains%22%2C%22value%22%3A%22sendBeacon%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A100%7D).
This has to do with imposed [data limits in the beacon API](https://w3c.github.io/beacon/#return-value):

> If the amount of data to be queued exceeds the user agent limit (as defined in [HTTP-network-or-cache fetch](https://fetch.spec.whatwg.org/#concept-http-network-or-cache-fetch)), this method returns false

It's somewhat fascinating that we are sometimes able to trace these errors (which contain the entire body of the failed beacon) **using** the beacon API. 🤔 I initially thought the problem was the size of individual beacon, but the docs say that it's rather a limit of what gets queued, which explains why we do manage to trace them after the fact.

I'll try to queue the beacons in smaller chunks, hoping that that prevents the total queue size from getting as big 🤔  and then we can compare the results in a few weeks to so if there are less failures.

**Comment by hahn-kev** [comment]
so `sendBeacon` is being used to send the telemetry, is there a fallback that we can use if that fails? Can't it just post via fetch?

**Comment by myieye** [comment]
@hahn-kev good question. So, the main benefit of the beacon API is that requests don't get cancelled on navigation, but I just discovered that [fetch with keepalive](https://developer.mozilla.org/en-US/docs/Web/API/fetch#keepalive) is an explicit replacement for that. So, I'll take a look.
