### ISSUE TITLE
Migration tweaks

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#314]
Nice to have before v1, but not strictly required for MVP, putting in mvp anyway for visibility.

- [x] Admin dashboard should add a column showing migration status (perhaps just an icon with hover tooltip to keep horizontal space usage down)
- [x] Admin dashboard should have a way to filter/sort by migration status
- [x] On project page, might be nice for the "Migrated" badge to have a green checkmark or a green background color to make it stand out a bit from the other black-background badges

**Comment by myieye** [comment]
Do we want normal users to see the migration badge? It's really just a DevOps / admin thing. We probably don't want users asking about it, so I'd suggest making it `<AdminContent>`. @rmunn FYI

**Comment by rmunn** [comment]
Further tasks to do, from feedback on #337:

- [ ] Warning banner on project page when project currently being migrated
- [ ] Edit IconStrings type to allow `"loading loading-spinner loading-${string}"` as another valid icon string
- [ ] Use that for the migration status icon on the project page

**Comment by rmunn** [comment]
#337 is finally ready to be reviewed and merged.
