### ISSUE TITLE
Write an integration test for S&R

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#32]
I'm hoping this is something we can automate in a test by consuming FLEx bridge the same way LFMerge does in order to run a S&R against our new Language Depo.

Down the line we could even push changes and receive changes as part of the test, but for now it could just be a simple test to check for changes and verify that there are none. 

Goals:
- [x] test hg exists
- [x] test FLEx bridge hg S&R
- [x] test resumable via FLEx bridge 
- [x] test failure for invalid credentials
- [x] test failure for missing permissions
- [x] test success for admin user not on a project
- [x] test failure for a project that doesn't exist

**Comment by rmunn** [comment]
Broad-strokes design notes:

Two tests are desired. First, using pure Mercurial with no FLExBridge, we do a pull of `http://hgweb/projectCode` and make sure the project can pull successfully. Second, use FLExBridge to do a Send/Receive (probably using the existing Language_Forge_Clone action, which does a pull but not a push).

At a future date, we'll want to also test pushes. To test pushes, we'll do a Send/Receive of the Sena 3 project in FieldWorks (pointed at our hgweb repo), and save the resulting Mercurial commit. Then the test scenario will load up the existing Sena 3 project, recreate the commit in question (by making the same changes to the same files), and push the result. Similar to the pull/clone testing, we'll run two tests, one with just Mercurial and one passing through FLExBridge (using the Language_Forge_Send_Receive action).

**Comment by rmunn** [comment]
@hahn-kev Send/Receive tests working now, though I'd like to discuss the design before it's merged. I've marked the PR as ready for review.
