### ISSUE TITLE
Turnstile expects users to click the checkbox on some playwright tests

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#322]
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/183fb2d7-fa6e-49a1-940c-8770b39c0f2b)

Right now we have checks on the server side to allow the playwright tests without validating the token. We need to add some additional checks on the client side.

**Comment by myieye** [comment]
This doesn't seem to be a problem.
Here's a screenshot from an Ubuntu trace (EmailWorkflowTests_2023-10-16T08-19-13) from [this run](https://github.com/sillsdev/languageforge-lexbox/actions/runs/6530621452), where the checkbox was displayed and the test just walked right through:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/406fdd0a-1697-47f5-999d-4ede742be19b)
