### ISSUE TITLE
project reset requires admins to upload a zip of the .hg folder

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#327]
- [x] determine how to upload a large zip through cloudflare. Chunked encoding or https://tus.io/
- [ ] update UI to let admins upload the zip
- [ ] track project reset status so an admin can resume in the middle if they didn't upload and closed the page.

if we need to use tus, here's the js client https://github.com/tus/tus-js-client and the dotnet server: https://github.com/tusdotnet/tusdotnet

**Comment by rmunn** [comment]
I just managed to prove that chunked encoding won't work. I took a 1.25 gigabyte video file and tried to POST it to one of our Cloudflare-protected URLs.

Without chunked encoding:

```plaintext
$ time curl -D - -X POST -T testme.mp4 -u robin_munn@sil.org:password_omitted https://hg-staging.languageforge.org/rmunn-sena-3
HTTP/2 413 
date: Tue, 17 Oct 2023 04:17:23 GMT
content-type: text/html
server: cloudflare
cf-ray: 8175b735de57e8f5-DFW

<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

real 2m48.680s
user 0m4.309s
sys  0m3.973s
```

With chunked encoding:

```plaintext
$ time curl -H "Transfer-Encoding: chunked" -D - -X POST -T testme.mp4 -u robin_munn@sil.org:password_omitted https://hg-staging.languageforge.org/rmunn-sena-3
HTTP/2 413 
date: Tue, 17 Oct 2023 04:23:38 GMT
content-type: text/html
server: cloudflare
cf-ray: 8175c0b63a3ab30f-BEG

<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

real 2m39.438s
user 0m4.350s
sys  0m4.920s
```

Neither one of those POSTs showed up in the Lexbox logs on staging. So we've proved that chunked encoding won't get around Cloudflare's hard limits on POST size.

**Comment by rmunn** [comment]
The limit is 200 MiB exactly. A POST of 209715200 (200\*1024\*1024) bytes goes through and gets an HTTP 200 from the server. A POST of 209715201 bytes, just one byte more than 200 MiB, gets a 413 Request Entity Too Large error.
