### ISSUE TITLE
last commit date not updating automatically for hg protocol

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#350]
the last commit date should be updated after every S&R, however it's not getting updated.

**Comment by rmunn** [comment]
The ProxyEventsService has an OnHgRequest method that's supposed to be doing this update when it sees an hg `unbundle` command go to hgweb. We'd need to check if it's actually running, and if so, if it's perhaps running too soon, before the hgweb container has actually finished processing the `unbundle` and created the new commit.
