### ISSUE TITLE
There are user accounts with the same username in redmine

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#362]
If there aren't collisions when migrating redmine data, we'll choose to make usernames case-insensitive.

It's fairly common for usernames to be case-insensitive, though not always the case.

- [x] users with different email and same user name are merged
- [x] notify users about merge

**Comment by hahn-kev** [comment]
it turns out there are collisions so we can't make names case insensitive. We also have conflicting names where the case is exactly the same. TBD how to solve that.

**Comment by hahn-kev** [comment]
fixed in 3f905b73c5a0290643190fb90f21e600bed8d3e4
