### ISSUE TITLE
Two-letter language codes should be allowed

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#380]
The language code `fr` was rejected:

![image](https://github.com/sillsdev/languageforge-lexbox/assets/90762/5b5817e3-b910-49f5-b41c-dc9218cffe30)

But [valid two-letter language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) should be allowed.

**Comment by myieye** [comment]
I think we want users to use three-letter language codes.
That's what [Ethnologue uses](https://www.ethnologue.com/codes/)/pioneered.

**Comment by megahirt** [comment]
There is more discussion to be had on the topic of language codes.  The language code could be two or three letters, and then there is the full "language tag" which is I think ultimately what we want to track for a project.  The language tag may have the script, region, and variant components, some of which are implied for certain languages.  WSTech maintains a library for managing and manipulating language tags.  check out https://github.com/silnrsi/langtags/blob/master/doc/tagging.md

**Comment by myieye** [comment]
Then there's also the fact that a project may involve multiple languages, even multiple vernacular languages, I think.

**Comment by megahirt** [comment]
Yes exactly.  We have never had a system that allows the project metadata
to store more than one language code AFAIK.  In this case and in the
historical case, I think the intent is that the language code refers to the
primary vernacular language.  There are a number of bilingual and
trilingual dictionaries out there that contain more than one vernacular, or
at least a vernacular + a LWC + a national language.

It would be awesome to capture that information in the project metadata.
This would of course be user supplied.  What would be really interesting
would be the ability to extract this info automatically out of the project
itself for "significant" chunks of data.  Many data sets have insignificant
writing systems configured that are barely used or functionally abandoned.
Those could be ignored.
Chris

**Comment by hahn-kev** [comment]
We could totally do that for at least FLEx projects. Not sure how much work it would be though. The question then is how often do we change for changes as obviously a user could add a vernacular language at some point.

**Comment by hahn-kev** [comment]
after discussing we will reduce the limit to 2 characters
