### ISSUE TITLE
Avoid hitting header size limits

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#387]
Related to #215.

Users with lots of projects (mostly only admins with up to 600+, but also none admins with up to 85) get JWT tokens that hit a header size limit imposed by Cloudflare (as well as potential limits imposed by Ingress).

We discussed various ways to fix this:
- Remove admins from all projects 💥 => still a problem for some non-admins
- Remove projects from the token => involves a decent amount of front-end and back-end work 🤮 
- Minimize the size of the token => this seems promising

E.g. we could reduce this:
```
{"Code": "test-race-flex--45cf1c7d","Role": "Manager","ProjectId": "45cf1c7d-e82e-42c2-b0ab-bed897d49299"},
```
to something as small as this:
```
"6000:M",
```

We think our current limit is ~50 projects. If we could get up to 500 we'd feel pretty safe.

Todo:
- [x] Determine the exact header limit on cloud flare (around 10,225 chars), 9,000 char jwt is the max
- [x] determine project limit with a way to check it automatically, 170 project limit
- [ ] encode the project list as a string with role and guid, no base64 encoding
- [ ] remove projects from admin jwt
- [ ] throw error when jwt is over 9,000 chars long so we don't get some obscure error somewhere else.

**Comment by hahn-kev** [comment]
Alright from some simple tests of requests (not responses). Here's my test code:
```c#
var stepSize = 1;
int headerSize = 10210;
for (; headerSize < 10_000_000; headerSize += stepSize)
{
    var response = await HttpClient.SendAsync(
        new HttpRequestMessage(HttpMethod.Get, "https://staging.languagedepot.org/api/healthz")
        {
            Headers = { { "test", RandomString(headerSize) } }
        });
    response.StatusCode.ShouldBe(HttpStatusCode.OK, $"header size: {headerSize}");
}
```
I get an error if the header is bigger than 10225 chars. To stay on the safe side I'm going to say our jwt can't be bigger than 9,000 chars. That should leave us over 1,000 chars of buffer space for anything else that might end up in other headers.

**Comment by hahn-kev** [comment]
My goal was to preserve the guid, as it would be a fair bit of work to change that, it would also be inconsistent with other tables which I'd also like to avoid. I was able to get up to over 300 projects using ascii85 encoding, but I'm not 100% sure I could decode that easily. A much more reasonable implementation got me to 258 projects. Here's what the project list looks like encoded:
```
mpxvAvOBbFUeP4equt7kxFg==|wRRM4Uk8xUqgP1y5A7aRyQ==,ezk224PgLSUe77ri1VkpHeA==|StBP6y9+MEavY+WsfHffGA==
```
this is just 4 projects. It's broken up into groups like this: `{roleCode}{projectId base64 encoded}|{projectIds...},{nextRole}{projectIds...}`
it's ugly to read and we can't just copy the project id out for testing or debugging. 

Without base64 encoding we fall down to 174 projects. But this is much more readable but at a big loss. Ultimatly this just needs to work until we implement orgs for grouping projects and then this problem pretty much goes away. 
| Encoding | Project Count |
|----------|---------------|
| base64 guid    | 258        |
| guid to string    | 174      |
| current limit | 68             |

**Comment by hahn-kev** [comment]
per team discussion we're going to go with the straight guid to string option, 170 projects is plenty.
