### ISSUE TITLE
Auto-fill create project form for admins

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#404]
When admins get a project request email, the button that takes them to the "Create project" page should automatically fill out the form with the details in the info.

Bonus: should we also automatically add the requesting user to the project?

**Comment by hahn-kev** [comment]
I like the idea of automatically adding them. We could even expose that to users with a simple table, like this:
| Email Address         | Role               |
|------------------------|--------------------|
| user@example.com       | Manager |
| anotheruser@example.com | Editor|
| yetanother@example.com  | Editor|
let them add more as they desire.
