### ISSUE TITLE
Add button to copy project code to clipboard

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#406]
We should add a button to copy a project's code to the clipboard (making it easier to "pick" that project in Chorus). Probably just here:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/029c0819-a6b8-464a-9500-ad01bda6828e)

Bonus:
Can/should it also be elegantly added in the "My projects" page or the admin dashboard?

**Comment by rmunn** [comment]
You'd think this would be trivial, but a quick look at https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript suggests that it's not as simple as it would seem. There are two APIs for copying text to the user's clipboard, one that's widely-available but deprecated, and one that's new and not necessarily safe to use in every browser yet.

I'm going to upgrade our size estimate from "Tiny" to "Small" for this one.

**Comment by myieye** [comment]
@rmunn We actually already have a [copy-to-clipboard feature](https://github.com/sillsdev/languageforge-lexbox/blob/157b420e02bd17d6588e2a045abe1f6904517e58/frontend/src/routes/(authenticated)/project/%5Bproject_code%5D/SendReceiveUrlField.svelte#L20). I was also somewhat overwhelmed when I tried to decide what API we should be using and if we needed to request permission and what not, but...I just went with the newer API and it seems to be working fine.

**Comment by megahirt** [comment]
For something small like this, I think it's fine to go with the new API and keep it simple.
