### ISSUE TITLE
Fix Markdown library

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#418]
We saw this error in production
https://ui.honeycomb.io/sil-language-forge/environments/prod/trace/tcP5jPJZNxW?fields[]=s_name&fields[]=s_serviceName&span=a159560987cf4939

restarting the container fixed the issue.

**Comment by myieye** [comment]
The problem came back a while after the restart.

**Comment by myieye** [comment]
It's coming from svelte-markdown, which overrides `console.warn` and only undoes the change on the client, i.e. the call-stack just grows and grows on the server.
Here's the code:
https://github.com/pablo-abc/svelte-markdown/blob/main/src/supress-warnings.js

**Comment by myieye** [comment]
I [patched the problem](https://github.com/myieye/svelte-markdown/commit/763a7200b20292e26b06bb236dbc6319e93dc0e2) in my own fork.
The patch is suboptimal. So is using a fork.
So, I'll try to get a better fix into the original repo.

**Comment by myieye** [comment]
I've opened a [PR for svelte-markdown](https://github.com/pablo-abc/svelte-markdown/pull/82).
We'll see what happens in the next while.
