### ISSUE TITLE
backend gives a 400 for empty password logins from FLEx and LF

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#419]
We'd like to return a 403 instead so we don't have a bunch of errors in our logs
https://ui.honeycomb.io/sil-language-forge/environments/prod/result/tZ2E1VxrXFt/trace/f1HJ5arUKqP?fields[]=s_name&fields[]=s_serviceName&span=ad411a11e931f1d6

**Comment by rmunn** [comment]
@myieye says this isn't actually fixed yet.
