### ISSUE TITLE
Add username/login to admin user table

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#423]
An admin has asked us to include the user logins that we migrated from Redmine in the user table.

I think that makes sense, because all users are currently using logins, and admins should be able to map logins to users.

@hahn-kev I feel like you have an opinion on this 😉.

Note: make sure the GQL filter can handle nulls.

**Comment by hahn-kev** [comment]
I'd like to avoid this since new users won't be getting usernames moving forward. I'd like to hear back from admins why they need to see it before we commit to this
