### ISSUE TITLE
Allow reset project without uploading modified data

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#428]
basically an admin just wants a clean slate. They don't want to modify the zip they downloaded, they just want to delete it and create an empty repo that they can push to for the first time.

**Comment by hahn-kev** [comment]
I'm thinking we just make the zip upload optional. Let them reset the project and then don't require the upload and then we're done.

We will have to add another api to set reset status to None, but that should be all we need to do to support this usecase.

**Comment by myieye** [comment]
That sounds very similar to what admins are used to which is a big bonus. I like it.

Just to remember:
That means big commits that are sometimes >200MB, which means the user would have to use resumable.
As long as admins know that we should be fine.

**Comment by hahn-kev** [comment]
Yeah that's no different from how the system worked before (the LF domain already had the 200mb limit).
