### ISSUE TITLE
Reset project feature does not give www-data permission to write

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#433]
If you reset a project here's what it looks like:
```
-rw-r--r-- 1 root www-data   57 Nov  6 13:53 00changelog.i
-rw-r--r-- 1 root www-data   12 Nov  6 13:53 requires
drwxr-xr-x 2 root www-data 4096 Nov 28 13:15 store
-rw-r--r-- 1 root www-data    0 Nov 28  2023 thgstatus
```
www-data doesn't have write permission, so hg can't write to it.

This resulted in a 500 for me locally and in prod.
Here's the prod trace: https://ui.honeycomb.io/sil-language-forge/environments/prod/result/ivH7fn9QdE5/trace/c2RQAJUJBs9?fields[]=s_name&fields[]=s_serviceName&span=cb990bdf6409bf24.

**Comment by myieye** [comment]
I know the least about this sort of thing, but
- if LexBox were running as user 33, then the umask would be 002 instead of 022, which sounds good, but that gave me an exception when it apparently tried to write to /var/www (a folder that I could never find 😆)

**Comment by hahn-kev** [comment]
good catch Tim, I don't think this should be difficult as we're already setting permissions when initing a repo, we just need to recurse though the `.hg` folder calling `File.SetUnixFileMode` on each file and folder.
