### ISSUE TITLE
Send/Receive requests are split into 3 traces

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#444]
I observed it here:
- [One](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-api/result/fnwy6242Egj/trace/AMYYN6ojoG?fields[]=s_name&fields[]=s_serviceName&span=6fddad01b29f735a) - Api - Our proxy? - Asp instrumentation
- [Two](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-api/result/fnwy6242Egj/trace/2X2EZ8ejwdq?fields[]=s_name&fields[]=s_serviceName&span=4fa28853b3b6e89f) - Api - Http instrumentation
- [Three](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-api/result/fnwy6242Egj/trace/m8yRN5Hy3rQ?fields[]=s_name&fields[]=s_serviceName&span=c9a46db70122a7c0) - Api - Asp instrumentation

I think we just need to make the proxy propogate its tracing context and that will make it "consume" the other two.

**Comment by hahn-kev** [comment]
I don't think that's the case. 

1. returns a 401, meaning they weren't authenticated properly, in this case probably there was no auth header, typical for basic auth the first request doesn't include the credentials until it gets a challenge back, which is also why there's no db traces in this one.
2. it goes through, you can see a 200, some queries and an http request to redmine
3. this is a request to /api/v03/pullBundleChunk where as the last 2 were to /api/v03/getRevisions, so it's clearly not the same request

Now it would be great if those were all traced together as part of a single trace, but that would require changes at the client side in Chorus.
