### ISSUE TITLE
Set up releases and release notes

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#448]
Releases are a great way to:
- See what happened when (for us as well as other stakeholders)
- Celebrate progress

I think we want to:
1) Create tags when a release is successfully deployed to prod
2) Create a release based on that tag
3) Have the release notes automatically generated based on our labels

There's a `deployment_status` hook we could use to create tags when a deployment is successful, but then I don't think we'd have access to our version label, so we should probably just add a step/job/action that we call to create a tag with the correct label. Then we create a release based on the tag.

There are lots of actions for generating releases.
This has the most stars: https://github.com/softprops/action-gh-release
More are listed on this archived repo: https://github.com/actions/create-release

And here's the first google result for an action for creating a tag: https://github.com/rickstaa/action-create-tag.

And here's how we configured generating release notes in LF-classic: https://github.com/sillsdev/web-languageforge/blob/develop/.github/release.yml

**Comment by hahn-kev** [comment]
attempted here: e7e7dca1c4af181285e09eca1a6a2f234d7cae62
We need to test it, which is complicated so we'll just release a new version and see what it does.
