### ISSUE TITLE
improve permission errors, special case project permissions

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#449]
User issue: User gets added to a project, whoever added them didn't tell them to logout, they refresh the home page and see the new project, however when they click the link they get a big ugly error.
[![image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/f8b214ba-fbd9-43a2-9125-3d131bde3726) trace](https://ui.honeycomb.io/sil-language-forge/environments/prod/result/yyqe494rDmX/trace/mZNJy2gUtKQ?fields[]=s_name&fields[]=s_serviceName&span=deb4da4eb6391180)

a couple of ways to improve:

- don't show a big ugly error on a permissions issue
- for projects suggest that they logout, or better yet, provide a button to refresh your token and try again
- when hitting the home page you will see all your projects, even if your jwt is outdated, we could detect that there's a mismatch between your jwt and the projects list (for non admins), if we do then we could automatically refresh the jwt.

This is kinda another problem with storing the project list in the jwt, but ultimately unless we want to always fetch that permission from the DB it'll need to be cached somewhere, so we can't really fully avoid this problem.

**Comment by myieye** [comment]
Note: Node doesn't actually need to get the updated token/project-list.
