### ISSUE TITLE
Improve JWTs for FLEx auth

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#455]
Related to #145.

We need to polish up how using JWTs in FLEx works.
- We want the tokens to expire
- We don't want weird errors when using an expired token
- We want tokens to use the refresh token
- If a user is added to another project, they need a new token
- etc.

**Comment by hahn-kev** [comment]
I'm going to just roll these changes into #442 since it makes way more sense to just include it with that
