### ISSUE TITLE
Certain screen sizes make it difficult to notice that tables are scrollable

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#461]
I talked to an admin today that couldn't figure out how to edit a user, beacuse the action button was out of scroll-view and there were ~70 users in their search result, so the horizontal scroll bar was very far down.

Some UX ideas:
- Move the scroll bar to the top with 2 `rotate(180deg)`
- Use a max height, so the table can never be too big
- Make the name of the user clickable, maybe with an edit icon

**Comment by hahn-kev** [comment]
Some other suggestions:
- make the table responsive (start removing columns at smaller sizes)
- limit column size and truncate data when it starts to get to long
