### ISSUE TITLE
Email footer not centered on mobile 

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#476]
Here's a screenshot from my phone showing the issue.
![Screenshot_20231212-174607.png](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/6e4047d9-6009-4ddb-922d-5c21a3ca486e)

**Comment by myieye** [comment]
🧪 I looks good in the Gmail app on my phone. It still looks bad in the Gmail mobile web app, but I don't think we want to try to make that work.
