### ISSUE TITLE
Design a way to view all user details

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#481]
currently there's a number of user fields that aren't visible in the system. Here's the list of properties that can't be viewed currently

- Localization code
- Last active
- can create projects
- locked
- created date
- updated date
- id (not sure if we want to show it)

There should be a way to display this information. Here's 2 designs of how we could show more information

bottom modal:
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/d6c29eec-eb5c-4811-9614-7956889ae353)

accordion style:
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/a08c5b42-c847-49fe-980d-10f802ea47ec)
maybe not exactly how we would display the info (and in this case there's obviously duplicates. Opened by clicking the name only one can be open at a time.

with both of these options we could open by clicking on the name, then we could display actions inline. I actually prefer this to the current menu on the right side, so if we could remove that completely I'd love it. 

@myieye what do you think?

**Comment by myieye** [comment]
As discussed we'll plan to go with the modal version:
- Easier to implement
- Easiert to resue on other pages (e.g. the project page)

**Comment by hahn-kev** [comment]
Alright I've implemented it. Here's a screenshot. There's some issues though
![image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/b04c91d1-9f5d-41b7-a881-688e031d378a)

1. using a button styled as a link to open the modal which means the text is upper case. This will probably change when we upgrade to daisy4
2. link color does not match project
3. link on project table opens a new page, but the link on the user table just opens a dialog, I don't like the inconstancy. Suggestions? I want to remove the dropdown menu and move those actions into the dialog and I like it being simple to open, but I want to stay consistent.

**Comment by hahn-kev** [comment]
results from our discussion

1. we shouldn't use a link due to it not opening a new page, use a button instead, small maybe with an icon
2. if we remove the overflow menu and put buttons on the dialog then it makes the edit case tricky. Do we open another dialog on top? or replace the contents of this dialog with another?
3. The filter is nice to have in the user list, leave it as an icon button that can be clicked with a tooltip on hover. We're ok with the UX trade off since this is an admin only page.

**Comment by hahn-kev** [comment]
- show details on project page for admins
- show button on the user table
- keep overflow buttons for now on user table
