### ISSUE TITLE
setup alert when a container is killed due to oom

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#482]
we've seen some test failures due to a pod getting killed due to going over the memory limit, we need to get an email when that happens otherwise it'll be really hard to determine if a test is broken or if there's just a memory issue.

**Comment by myieye** [comment]
For the record, the [oom's I observed](https://github.com/sillsdev/languageforge-lexbox/issues/297#issuecomment-1856168895) only resulted in a process getting killed, not a pod.

**Comment by hahn-kev** [comment]
Fair, but I've seen pods in staging get killed due to oom.

**Comment by myieye** [comment]
Unsurprisingly it looks like I don't have any permissions to do this sort of this:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/bf6dfdaa-3302-4926-b3aa-73d8cc9e5675)

But, it does look like we're helf way there:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/d2eb5d0b-c90a-40a5-902f-d761901aa6d2)

**Comment by hahn-kev** [comment]
yeah this has actually be in process with LTOps for a bit, I'm now getting emails so we could probably close this. LMK if you want to be on those emails too
