### ISSUE TITLE
Update S/R tests to use Chorus 6.0.0-beta0043 or later

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#487]
The NuGet Chorus packages (SIL.Chorus, SIL.LibChorus, etc) from 6.0.0-beta0043 onwards now have Mercurial 6.5.1 included. We should update our Send/Receive tests to use those package versions, to make sure that everything still works properly with a Mercurial 6.5.1 client.

**Comment by hahn-kev** [comment]
sounds like a great idea. I do want to make sure that we run our integration tests using hg 3.3 and hg 6.5, this will mean making some changes to how our tests are run to achieve this.
