### ISSUE TITLE
admin confused at not seeing project request in UI

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#506]
User A tries to create a project, they don't have permission so it goes out as a request. They ask their org admin (who's a LD site admin), who then logs in and can't see the project request.

Off the top of my head the way to fix this is to create the project as a draft and just send an email to notify the admin it's been created and let them approve it or rename stuff (including code) before approval.

**Comment by myieye** [comment]
Just for the record, this is a very technical detail, but it suddenly seems very wise to me to use a seperate DB table (as @rmunn also suggested, I think) for draft projects. I think that handling project-codes for draft projects in the same table as real projects is bound to be messy in some way no matter how creative we get, not to meantion all the fields that would be meaningless for a draft project.
