### ISSUE TITLE
Fetching _app/version.json sometimes fails

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#533]
An [example failure](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-sveltekit-client?query=%7B%22start_time%22%3A1706625324%2C%22end_time%22%3A1706764423%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22error%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22app.user.id%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%220b2c5ef6-1faf-4b2e-acf1-d3a647670664%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A100%7D) among a horde of successful requests:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/9db9bedc-ffe1-4709-aca7-2895a3fc6ac1)

Another [similar example](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-sveltekit-client?query=%7B%22start_time%22%3A1706583561%2C%22end_time%22%3A1706648382%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22error%22%2C%22exception.message%22%2C%22window.navigator.user_agent%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22app.user.id%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22fc2cea5d-c32d-445e-96b1-4ed21c911d17%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A100%7D):
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/8e22225d-9873-46af-acfa-4b750845e8be)

And [another example](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-sveltekit-client?query=%7B%22start_time%22%3A1706619086%2C%22end_time%22%3A1706640509%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22error%22%2C%22exception.message%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22app.user.id%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22d5c804fa-db96-42cb-bcc1-478ec4521cd3%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A1000%7D):
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/45639b1d-f595-484b-ad0f-f24f53d9ad79)

And here's [@hahn-kev](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-sveltekit-client?query=%7B%22start_time%22%3A1706578800%2C%22end_time%22%3A1706581223%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22error%22%2C%22exception.message%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22app.user.id%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22eb9a54e0-3a0a-4331-8f41-7145d89d7b3b%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A1000%7D):
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/b9a8117b-4d84-446c-a9e4-771a7d94ef03)

In all of these examples it seems we're dealing with an idle tab: the **only activity** by the user over a prolonged time period are the periodic requests to _app/version.json.
And there are gaps between batches of requests. Because the user is idle, the gaps must suggest unstable internet.

So, I think the pattern is:
- A request for _app/version.json fails, beacuse the client is offline
- The client comes back online
- Sending the telemetry of the failed request works, beause we're now online
- Future requests to _app/version.json work as well

**Comment by myieye** [comment]
So, this looks harmless to me. Especially considering that these are not critical requests.

I'm tempted to just turn these off.

The alternative is:
1. Getting the fetch url (which we should maybe already be doing. Currently it's only on the second span, which isn't marked as an error)
2. Just throwing the error away if the fetch is to _app/version.json

**Comment by hahn-kev** [comment]
turn what off? the version fetch?

**Comment by myieye** [comment]
Sorry. Yes, turning off the new version poll. It's not particularly valuable, though I should revisit that issue.
