### ISSUE TITLE
Emails not being translated

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#534]
(I'm currently just assuming that I've triaged this correctly)

In https://github.com/sillsdev/languageforge-lexbox/pull/516 I moved out i18n initialisation from the hooks to the root layout (because that made it easier/possible to pick the correct locale).

The root layout doesn't get used when we generate emails, because we only render individual components. So, now i18n never gets initialised and emails look like this:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/80243322-adcd-4686-865b-cc3f7edaf91e)

**Comment by hahn-kev** [comment]
I'm not seeing this when I run our automated tests for email. Do I need to change the language away from English?

**Comment by myieye** [comment]
I understand now:

There's a shared server-side singleton for i18n. I only stumbled accross this, because I was running the UI locally, but emails are still getting rendered in an instance of the UI in k8s. The UI in k8s never had a page load, so i18n never got inistialized.

If you run everything in k8s, it should be virtually impossible to reproduce this.

**Comment by myieye** [comment]
Will be covered in #545
