### ISSUE TITLE
Initial email verification email link is still valid after use

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#548]
We made it so that an email verification link that verified the user's current email address never expires.
However, it **should** expire if the user has already used it, otherwise the can use it again and again.
So, this:
```
if (user.Email != loggedInContext.User.Email &&
            user.UpdatedDate.ToUnixTimeSeconds() != loggedInContext.User.UpdatedDate)
```
should become this logic:
```
var alreadyUsed = user.Email == loggedInContext.User.Email && user.EmailVerified;
if (alreadyUsed || (user.Email != loggedInContext.User.Email &&
            user.UpdatedDate.ToUnixTimeSeconds() != loggedInContext.User.UpdatedDate))
```

**Comment by hahn-kev** [comment]
FYI the jwt used does expire after 3 days. Changed the title to reflect that.

**Comment by myieye** [comment]
Then....hmmm, is this even worth changing?

**Comment by hahn-kev** [comment]
probably not tbh.
