### ISSUE TITLE
Partially completed project reset can leave dialog in unusable state

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#549]
While [creating an integration test for the project reset feature](https://github.com/sillsdev/languageforge-lexbox/issues/440), I cancelled the project-reset process for Sena 3 at step 3 (uploading a new .zip file into the project). From that point on, any time I opened the "reset project" dialog, it would start on step 3:

![image](https://github.com/sillsdev/languageforge-lexbox/assets/90762/093ed1a7-6d89-4806-9d64-7cf70e5fe993)

Even re-deploying by running `task up` (which runs `skaffold dev`) then refreshing the browser page didn't change this: the reset project dialog was still on step 3 after loading the project page in a new browser tab for the first time.

This happened on a per-project basis: opening the dialog for a different project placed the dialog in step 1 as it should be.

**Comment by myieye** [comment]
IMO this is by design. It seems desireable to me to force a user to consciously complete step 3 rather than implicitly leaving the project empty.

**Comment by rmunn** [comment]
Just figured that out myself. I've started resetting the test by uploading a sena-3.zip file manually if it fails partway through.

I'll need to take this into account as I flesh out the E2E tests for project reset, because with this feature a test that times out halfway through (between the project reset and the upload step, for example) could leave the tests in a state they don't expect. However, a properly-designed test fixture ought to be able to take care of that.

Anyway, closing this issue because it's not a bug after all.
