### ISSUE TITLE
500 status from updateLexEntryCount in prod

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#551]
Honeycomb [trace](https://ui.honeycomb.io/sil-language-forge/environments/prod/result/4wAEc8w7PAy/trace/ALa3s6Ma4Ru?fields[]=s_name&fields[]=s_serviceName&fields[]=c_http.status_code&fields[]=c_graphql.document.body&span=f5affd90510628cc)
```
23505: duplicate key value violates unique constraint "PK_FlexProjectMetadata" DETAIL: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
```

**Comment by hahn-kev** [comment]
Yeah I've seen this too, but only in tests, I believe it's a race condition between these 2 lines: https://github.com/sillsdev/languageforge-lexbox/blob/f89fc2c4cf49775ebd1f6802794f8172c1e56f4c/backend/LexBoxApi/Services/ProjectService.cs#L94-L100

It's not clear to me if this problem even needs to be solved.

**Comment by myieye** [comment]
We do seem to be having problems with this feature: https://sil-language-software.slack.com/archives/CGDKZ7NTV/p1708011899446579

@rmunn FYI

**Comment by myieye** [comment]
Actually, most projects do seem fine to me. So, I jumped the gun on this, but I still can't explain the example I linked to in Slack above.

There are some rather insignificant sources of weird data:
- Projects labeled as FLEx that are actually WeSay/LIFT projects (there seem to be quite a few of these 😬. People are presumably just in the habit of adding `-flex` to the end of project codes.)
- Projects that aren't migrated yet, get a project count of `NaN` 🤓
