### ISSUE TITLE
Default form validation error messages don't use user's selected locale

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#582]
For form validation where we don't explicitly specify the message, it (presumably) uses the user's browser locale.
(should we have done that? 🤔 😨 😆)

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/86e7b5ec-a0e2-4294-a070-1ff6b107756c)

**Comment by megahirt** [comment]
The browser locale seems reliable as to what the user would want.  Since we
are setting the user profile locale as a separate setting, maybe we should
offer to update the user's locale from the browser locale if they are
different?
