### ISSUE TITLE
Debounced project-code validation is causing trouble 😢

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#595]
The changes to the project name are within the same "debounce group" as the on-blur validation of the project code and so, the final debounced validation result seems to use the initial value of the name field (i.e. empty)...or something like that 😕 🤮 

https://github.com/sillsdev/languageforge-lexbox/assets/12587509/a9e00ae2-9aae-477c-b1f3-6657b5961979

**Comment by hahn-kev** [comment]
Making this a v1 issue.
