### ISSUE TITLE
User CRUD for admins

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#6]
Admins need to be able to fix or change things for users.

- [x] list users
- ~add new users~ @myieye: I don't understand this use case. Users should register themselves. It's also not mentioned in the MVP requirements doc.
- [x] delete users
- [ ] lock user
- [x] update user password
- [x] update user email

**Comment by rmunn** [comment]
@dadukhankevin Please leave a comment on this issue so I can assign it to you. Thanks!

**Comment by dadukhankevin** [comment]
Thanks! Here is a comment!
