### ISSUE TITLE
Write code to programmatically check if our translations are up-to-date

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#602]
I've found it easy to forget to update `es.json` and `fr.json` when adding new strings to `en.json`. And those are both languages that I can either speak, or at least read — and which are easy to get decent translations for from Google Translate or other services. Once we add more localizations, in languages (and/or scripts) that we don't read at all, it will get even easier for our translated JSON files to lag behind.

One thing we could do to help is create a tool that will parse the en.json file and print out:

- All keys present in en.json that are missing from at least one other translation files (and which files they're missing in)
- All strings that are identical in en.json and other translation files (because it may mean someone copied the English string over to avoid getting a runtime error, but that string is not actually translated)
    - We may eventually want to make an exception list for strings that are often the same in many languages, such as "Code" or "E-mail". That would be on a per-language basis, though, because (for instance) the French word for "code" is also "code", but the Spanish word is "código". So we'd want the exception list to contain "fr.admin_dashboard.column_code" but not "es.admin_dashboard.column_code".

**Comment by rmunn** [comment]
We'll probably want a command-line tool written in Node.JS, which would output a list of keys missing from each file. By default in text form, but optionally in JSON form as well.

**Comment by hahn-kev** [comment]
We actually want to integrate with Crowdin at some point, so I'm not sure I want to spend time on building tooling for manual translations.

**Comment by megahirt** [comment]
I am in favor of closing this issue and scheduling #903
