### ISSUE TITLE
Pass JWT lifetime into email rendering template somehow

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#619]
In https://github.com/sillsdev/languageforge-lexbox/pull/603#pullrequestreview-1905164876 Kevin suggested passing the token lifetime into the email template in order to render an appropriate number of days (currently the text hardcodes 3 days). That's slightly more complicated than it appears at first glance, because we'll have to get the JWT out of the URL passed to the template and then parse it to extract the expiration date. Also, it's possible that we may choose to give some JWTs might have a lifetime in hours, so we might want the text in en.json to be able to handle time specified in either days or hours. (I doubt we'll be sending emails with an expiration time of N minutes, outside of E2E tests, and in E2E tests we'd want the expiration warning text to be the same as that of the regular text).

This issue is to track that remaining work that didn't make it into #603.

**Comment by hahn-kev** [comment]
FYI no need to parse the JWT, we can just return the lifetime of the JWT out of the function that generates it and pass that value into the render code.

**Comment by rmunn** [comment]
Yeah, I see how to do that by modifying the parameters, e.g. public record ForgotPasswordEmail(string Name, string ResetUrl) would become public record ForgotPasswordEmail(string Name, string ResetUrl, int expirationDays).
