### ISSUE TITLE
gql 403 when navigating home results in a redirect loop

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#632]
See the automated test failure here https://github.com/sillsdev/languageforge-lexbox/runs/22246037255

When clicking to go home, a request is made to gql, this will return a 403 which is intended to logout the user. However it redirects the user home, however the user got this error trying to go home, so this also fails. The reason it's being sent home instead of logout is because it's determined that the user is not home because the url is `/user`, the url doesn't change until after the gql request succeeds.

One odd thing is that it looks like the hooks server and hooks client has a very different determination of when a user is home or not. On the server side a user is determined as home if they are under the `(authenticated)` route, where as client side it's just if the url is `/` or `/home` or `/admin` which makes sense for home. Should the parameter be renamed to represent something else?

**Comment by myieye** [comment]
The server-side check is: `routeId.endsWith(AUTHENTICATED_ROOT)`. So, it's not if they're anywhere under the `(authenticated)` route, but rather only if they're exactly at that route, which is equivalent to `/`.
