### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: googletag

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#638]
The error is caused by the [Stands ad-blocking Chrome extension](https://chromewebstore.google.com/detail/adblocker-stands/lgblnfidahcdcjddiepkckcfdhpknnjh).
I typically have to wait about 30s after a page load before the error appears.

We have code that tries not to show errors from browser extensions. Apparently it's not good enough.

It looks like 2 errors are triggered and we successfully mute the first one, but the second one gets displayed. Here's the console output:
```console
Uncaught SyntaxError: Identifier 'observeDomChanges' has already been declared (at ruleApplier.js:1:1)
VM208:1 Uncaught TypeError: Cannot redefine property: googletag
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:196
    at <anonymous>:1:524
(anonymous) @ VM208:1
(anonymous) @ VM208:1
```

Perhaps we can just filter out errors with [VM scripts](https://stackoverflow.com/questions/17367560/chrome-development-tool-vm-file-from-javascript) in the stacktrace?

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/07af0d04-53d2-470e-86e9-70ab3297f884)

**Comment by hahn-kev** [comment]
I'm not sure filtering out VM errors is a good idea. VM just indicates that the code isn't associated with a file, for example if you use eval or new Fuction then the code executed there will be reported as being from VM. I'm not sure if we're doing that in our code today (or if a lib is) but I'm not sure what the fallout would be of that.
