### ISSUE TITLE
Allow bulk-deleting users

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#641]
Once https://github.com/sillsdev/languageforge-lexbox/pull/621 is deployed, admins are going to want to bulk-delete users. I suggest two ways to do it in the UI. One is to put checkboxes next to each line in the users table, and have a "Delete Checked" button. Another is to have a search filter for "Users I created" in the admin dashboard, and a button for "Select All" that will select all the users in the current view (and then you can click "Delete Checked" to get rid of them).

Bulk deleting will, of course, pop up a warning saying "You are about to delete N users. Are you sure?" And perhaps if any of them are project managers, bulk-deleting is not allowed.

But at the very least, admins are going to want a way to manage the users they created, and a way to easily delete them at the end of the conference or workshop or whatever. Maybe with exceptions for those that have changed their password or verified an email address or otherwise promoted their account status.

**Comment by rmunn** [comment]
Another use case for bulk deletion: we appear to have quite a few spam/fake accounts, with names like AcNxbNEMxjUW. If an admin wants to clean those up, right now that would be a tedious process of clicking on each user, clicking on "Delete User", typing DELETE USER into the box, clicking Confirm, rinse and repeat. It would be nice to give them the ability to check multiple checkboxes then delete all the checked users at once.

**Comment by hahn-kev** [comment]
I plan to clean up those spam accounts myself by executing SQL against the prod db to delete any user created before we migrated who isn't added to a project.

**Comment by rmunn** [comment]
Per comments in https://github.com/sillsdev/languageforge-lexbox/pull/683#issuecomment-2032843086 and https://github.com/sillsdev/languageforge-lexbox/pull/683#issuecomment-2033280185, this might not be desirable. I'll leave the issue open until we can discuss it at a team meeting.
