### ISSUE TITLE
Break up big repo folder by first letter

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#651]
related to #646 

Currently all our repos live in one folder, sadly this seems to cause poor performance for hgweb. After doing some testing it looks like we can work around this issue by grouping projects into smaller folders. I propose grouping by the first character of the project code, after doing some testing this seems like it will alleviate the performance issue.

this would mean changing the hgrc, currently it has this defined:
```
[paths]
/ = /var/hg/repos/*
```
this would change to 
```
[paths]
/a/ = /var/hg/repos/a/*
/b/ = /var/hg/repos/b/*
# etc...
```
we may need also need to include 0-9 and `-` as folders could start with those characters.

We would then need to make a lot of changes in our `HgService` to have it prefix any http request and any file access to prefix with the first character in the project code. I think we will need to redirect non hg requests to /hg/sena-3 to /hg/s/sena-3 in order to prevent css loading issues. 

I think the trickiest part of this will be actually moving the folders without breaking anything. Ideally we just change all the code we need and release the new version, but I'm not sure then when we would actually move the folders. Can we move them ahead of time and write code that works wherever the folders are? or do we move the folders and symlink the old location so that both locations work until the new code is deployed? I'm open to suggestions. I have confirmed that hgweb will follow symlinks.

~~We also need to test resumable to see how it works with this solution.~~ Works fine we just need to rewrite the `repoId` query parameter from `repoId=sena-3` to `repoId=s/sena-3` and the resumable server seems to work just fine.

**Comment by megahirt** [comment]
Nice find!  What evidence is there that this is the root cause of the
performance issues?

We should do a bit of research on current folder names, e.g. do any start
with an unexpected character like a Unicode character or a digit?  Then
enforce in the UI our policy that codes only start a-z.

Also, you've done some amazing magic with transparent URL stuff, I wonder
if you could somehow keep all URLs the same but transform them just before
hgweb gets them?

**Comment by hahn-kev** [comment]
Thanks, well I added 4,000 projects to the develop environment and it started having poor performance, so that's what's pointing me at that being the issue. I'm still not sure why it was fine before and then went bad, that's a mystery to me, but I suspect that we just didn't really notice with the default refresh time?

You're right we do need to check existing projects, currently we only allow letters, digits and `-` so I just allowed those as the folder names.

Yes the urls are 99% transparent to the user. The only time you would see it is if you go to the hg web UI, and click on a URL, hg web renders the page with links that have the path where it's hosted and I don't want to rewrite responses from the server.

**Comment by rmunn** [comment]
Beware of naming a folder `-` or any name that starts with `-` as it can cause all sorts of issues with shell scripts that aren't paranoid enough about file names. E.g. in many Linux commands, the name `-` means stdin or stdout, and it's a little difficult to get those commands to recognize that you meant an actual file/folder named `-`.

Also, names starting with `-` can cause behavior changes in commands that use glob patterns without being careful:

```plaintext
echo "Hello" > a
echo "there" > b
ls *
# prints "a b"
echo "Look out" > -l
ls *
# Behaves as if you had typed `ls -l a b`. Does not list the `-l` file but does change behavior of ls
```

This is actually an attack vector for some security attacks: create a file named `--disable-security` or whatever and then get someone to run a command with `*` in it in that folder.

For all these reasons, I'd **strongly** recommend that we forbid `-` as the first character in project codes. They can start with alphanumerics, but `-` may not be the first character.

**Comment by rmunn** [comment]
Better example: if someone creates a project code called `--insecure` then we might end up running `hg --insecure` which would mean "do not verify server certificates", which might be part of a DNS-poisoning attack designed to make us send user credentials to a hostile server somewhere. Note that this is an attack vector that we're **currently vulnerable** to, and I only thought of it when I noticed the discussion about `-` as the first letter of project codes.

**Comment by megahirt** [comment]
Robin, how about a PR for the UI that requires the project code to start
with a-zA-Z0-9 ?

**Comment by rmunn** [comment]
@megahirt wrote:
> Robin, how about a PR for the UI that requires the project code to start with a-zA-Z0-9 ?

Done, #653.
