### ISSUE TITLE
Update project meta data in a job

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#665]
We currently update the last-commit timestamp of a project in the context of a push request.
We don't want users to have to pay for this task, so it should be handed off to a job.

It is probably time to also update the lex-entry-count in the same job.

**Comment by hahn-kev** [comment]
There's already a job for this, just needs to be setup https://github.com/sillsdev/languageforge-lexbox/blob/51946e22f85f572bf9810780e6c91aa095be927d/backend/LexBoxApi/Jobs/UpdateProjectMetadataJob.cs#L6-L26

**Comment by rmunn** [comment]
Was there a reason this was reopened? If it's in the "Done" column now, I'm assuming it should be closed.

**Comment by myieye** [comment]
It will only really get turned on with the deployment of #729, so I'm using this issue to represent that and remind us to test and such.

**Comment by myieye** [comment]
Nevermind, #729 IS an issue. I guess I was just confused.
