### ISSUE TITLE
Invite user to project uses localhost as the return url

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#668]
the return url should not specify a host and should instead be a relative url.  The problem code is here: https://github.com/sillsdev/languageforge-lexbox/blob/ce3efe92532e86b118494eb328136a16b3173163/backend/LexBoxApi/Services/EmailService.cs#L125-L129

**Comment by hahn-kev** [comment]
We should also write an integration test for this so we can be sure that our email invite is working.

A fix for this would be to change the urlBuilder line to this:
```C#
var returnTo = (new UriBuilder() { Path = "/register", Query = queryString.Value }).Uri.PathAndQuery;
```

**Comment by rmunn** [comment]
I tested this back when I wrote that code, but I didn't realize that the `http://localhost` in the return URL was actually hardcoded localhost coming from UriBuilder. I simply thought that it was coming from GetUriByAction.

I'll write a Playwright test verifying that the `returnTo` path is indeed a relative URL.
