### ISSUE TITLE
Add init system to containers for better shutdown speed

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#67]
When you run `docker compose down`, two containers consistently take a little over 10 seconds to shut down: `lexbox-hasura-1` and `lexbox-lexbox-api-1`. That just-over-10-seconds time is a dead giveaway to the cause, because Docker Compose sends SIGTERM first, then 10 seconds later if the container hasn't shut down it sends SIGKILL. Neither one of those containers is running an `init` process to handle Unix signals, so the SIGTERM goes ignored. That means that:

1. Neither container is cleaning up after itself properly, and
2. Shutdown takes longer than it needs to.

There may be other situations where we will need those boxes to handle Unix signals in the future, so it's worth spending a bit of time making sure they have an init system in place. The appropriate init system for any given box depends a little on what it's running, but `tini` is often good. See https://github.com/sillsdev/LfMerge/pull/275/files for one example of modifying a container to run `tini` as its first process, and having `tini` launch the rest of the processes.

**Comment by rmunn** [comment]
Tini is actually built into Docker Compose these days, so all you have to do is add `init: true` in a container's specification to get it running with tini. This is not a long-term solution as it won't work with Kubernetes (see the https://github.com/kubernetes/kubernetes/issues/84210 discussion for details). The long-term solution will be to change our Hasura and API container builds to include `apt-get install tini` followed by `ENTRYPOINT [ "tini", "--", "/path/to/docker-entrypoint.sh" ]`. Then our Kubernetes environments will be able to use the exact same container image as Docker Compose. But for a quick solution to the problem while we're still doing most of our testing locally on dev machines, a two-line fix to docker-compose.yaml will be enough.

**Comment by hahn-kev** [comment]
Thanks for checking this out Robin, I feel like the dotnet container should respond to sigterm correctly and if it doesn't we can fix that fairly easily, hasura is another story though so we may have to go that route.
