### ISSUE TITLE
we are not notified when hgweb does not deploy properly

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#672]
None of the hg commands are working in prod:
- lexentrycount
- verify
- recover

Strangely they're working fine in develop and staging 😕 

Example [prod project](https://languagedepot.org/project/testlangproj-ih-flex)

**Comment by rmunn** [comment]
I bet this is related to the command-runner.sh script. Does the version deployed to prod expect repos in /var/hg/repos/sena-3 or in /var/hg/repos/s/sena-3?

**Comment by myieye** [comment]
Staging and prod are currently on the exact same version.
Repos are now in `/var/hg/repos/s/sena-3` everywhere AND have symlinks (e.g. `/var/hg/repos/sena-3 -> /var/hg/repos/s/sena-3`

So without digging, it feels quite baffling.

**Comment by myieye** [comment]
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/a59f149e-64af-4374-84c0-bb1d335ff017)

So, yeah, the command-runner is not working.
And the difference between prod and staging is that the symlinks are gone in prod. I guess @hahn-kev removed them.

But the real issue is that the command runner.
Apparently my script change didn't work, but we didn't notice, because the symlinks rescued it.

**Comment by myieye** [comment]
Well, here's the problem actually. Prod is still using an old hgweb image:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/4e5baff2-04d5-4304-ba11-c012e529cfc9)

**Comment by myieye** [comment]
So apparently we were asking for too much memory?
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/95629cea-2caa-473f-b704-1f43fcb606ae)

As a quick fix, [I decreased resumable](https://github.com/sillsdev/languagedepot-deploy/commit/d33655a11d6397bde13443268a18cbdb86294e7e) by 200mb.

The newer version is now deployed 🎉

**Comment by megahirt** [comment]
So the deployment "failed silently" in a certain way and we didn't have a
way to be notified, correct?

**Comment by g3mackay** [comment]
Well I don't know how easy it would be as it would take some testing, but there are several prometheus metrics that could probably be used to build an alert.  Metrics like: kube_pod_container_status_running or kube_pod_status_ready looking at the pods, or maybe kube_deployment_status_replicas_available, kube_deployment_status_replicas_updated, or several others looking at the deployment.  There may also be existing rules that come with rancher that could be leveraged.

**Comment by hahn-kev** [comment]
We can solve this ourselves by using the command script to make a health endpoint and return the version just like we do with other containers, then we can call that on deploy just like we do for the lexbox API and svelte kit containers.

**Comment by hahn-kev** [comment]
@g3mackay can we increase our memory limit so we can leave the memory at 1gb?

**Comment by hahn-kev** [comment]
I've renamed this issue as the problem was caused by hgweb not deploying. I'm making a PR so the api health depends on hgweb running the same version.
