### ISSUE TITLE
Add rules for when a user cannot be deleted

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#684]
In general, we probably don't want to allow user accounts to be deleted if they are the last manager on a project, similar to the decision we made in https://github.com/sillsdev/languageforge-lexbox/pull/592#issuecomment-1951991187. Currently the "delete user" logic doesn't check that rule, so it's entirely possible for a user account to be deleted while it was the last manager on a project. This would leave the project managerless.

We may want to add logic to the "delete user" mutation to disallow deleting users if they were the last manager on a project. We would also use that logic when implementing the backend part of #683.

**Comment by myieye** [comment]
In our April 3rd team meeting, we decided that we're not currently planning on implementing this.
I think the main reason is that there are currently multiple ways to get a project with no members.
