### ISSUE TITLE
Bulk create should support email addresses

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#691]
Our bulk create feature should support email addresses, because having email addresses is **our preference**.

I talked to an admin the other day who had just added a bunch of users (5+) to a project. The bulk add/create feature wasn't available yet.

She had given all the users (legitimate) email addresses. If she had used the bulk create feature she would not have assigned them email addresses (because it's currently impossible) even though she could have. Perhaps she wouldn't have even if she could, but it would sure be nice if it were possible.

There are a lot of fine details here:
- We need separate validation on usernames and on emails
- We should actually send verification email to the users who we populate the email field for (we claim that we did in the UI)
- If we use the entered value as an email address, then we probably shouldn't also populate the username column, because it doesn't correspond to our (somewhat unofficial) username validation rules.

**Comment by hahn-kev** [comment]
I'm 99% sure the bulk add supports email, looking at the code I'm pretty sure that's the case. Do we just need to explain that in the UI? @rmunn can you confirm?

Is there a bug that prevents adding users by email?

**Comment by myieye** [comment]
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/2db78aa9-3d77-4adc-a713-6e9f31fe435c)

**Comment by hahn-kev** [comment]
oh weird, so the backend supports email addresses, but you can't use them on the front end, I didn't realize that.

**Comment by rmunn** [comment]
Guestimating this as Medium sized because of the many different bits of validation/verification this is going to touch. The actual frontend changes will be quite small, but I'm guessing there'll be quite a bit of work needed on the backend to make sure we get this right.

Feel free to change this issue to size Small if you think I'm overestimating the work involved, of course.

**Comment by rmunn** [comment]
https://github.com/sillsdev/languageforge-lexbox/pull/697 is ready for review now.
