### ISSUE TITLE
client-fetch error: The user aborted a request.

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#701]
In the [last 60 days](https://ui.honeycomb.io/sil-language-forge/environments/prod?query=%7B%22time_range%22%3A5184000%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%22app.error.source%22%2C%22app.error.show_user%22%2C%22exception.message%22%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22app.error.source%22%2C%22op%22%3A%22exists%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%7B%22op%22%3A%22COUNT%22%2C%22order%22%3A%22descending%22%7D%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A1000%7D) we've had 88 occurences of the error: "The user aborted a request.".
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/f0bd8cfe-c3e0-467a-bf7c-1b2c8582e090)

At least 18 users have had it thrown in their faces:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/2c260c6c-ab8b-49d5-8f77-3304311c9331)

Examples: [one](https://ui.honeycomb.io/sil-language-forge/environments/prod/result/e9AgJDPY2mA/trace/qqrHJkGy29k?fields[]=s_serviceName&fields[]=s_name&source=query&span=622af18454948158), [two](https://ui.honeycomb.io/sil-language-forge/environments/prod/result/e9AgJDPY2mA/trace/FoMWEwY7pKC?fields[]=s_serviceName&fields[]=s_name&source=query&span=32a588baab09f9a0)

**Comment by myieye** [comment]
### 1. What should we do about these well-known URLs that are getting hit from wherever

Presumably we should just do: nothing.

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/44fd4545-fc75-4415-b0a8-c08dd2417dd7)

It looks like the crawler has come about 4 times:

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/8ec317ec-56b8-41c1-a0d9-25ccc0b4d79f)

### 2. I'm assuming the GraphQL occurences are all from querying project changesets

I forced this error locally like this:

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/6f29b6ef-eefc-4223-84a2-906ab1527ebd)

And my trace is the only trace in all existence that gets a root span with the exact error text: "[Network] The user aborted a request."
I think all the other occurences are missing the root span, which is the span created by our GQL `tracingExchange`.

So, I'm guessing:
1) This is triggered when the user closes a tab and we don't get the chance to call `operationSpan?.end();`
2) It won't happen nearly as often now that prod is fast again. This Graph suggests that that has so far proven true:

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/1e332091-0e11-453d-a854-0ecd30e84cd8)

So, I think we should assume these occurences will basically go away.

### 3. The top row is essentially duplicates of the other rows.

**Comment by megahirt** [comment]
your assessment sounds reasonable to me.
