### ISSUE TITLE
API won't upgrade in staging due to memory limits

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#705]
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/7876527e-6bea-4bfb-a9c7-3f32adf62295)

**Comment by hahn-kev** [comment]
FYI this isn't ever just a specific container/pod, it's just whichever gets caught out last since the limit is on the whole namespace. Basically we just need to increase the limit on the ld namespace/project

**Comment by myieye** [comment]
Thank you for clarifying that. After your comment and some time with my buddy, ChatGPT, I finally understand these numbers 😆.

So, now for my personal benefit and to try to explain what happened here...

So, the deployment has now worked and settled and we're currently using in staging:
```
   350Mi (api - lexbox)
   100Mi (otel - lexbox)
   150Mi (ui)
   400Mi (hgweb - hg)
   400Mi (hgresumable - hg)
 + 100Mi (db)
-------
= 1500Mi 
```

1500Mi is well under our limit, which is currently set to the interesting value of: `2560Mi`.

But during deployment, we have multiple instances of containers running in parallel, because we want to make sure that the new containers are running before we shut down the old containers. So, we theoretically need double our standard usage: `1500Mi x 2 = 3000Mi`.

When lexbox failed to deploy it was trying to add `450Mi  + 2300Mi = 2750Mi > 2560Mi`. But `2750Mi < 3000Mi`. So, there were `250Mi` that had presumably already been recovered from containers that had successfully started the new container and shut down the old container. Presumably `ui` (`100Mi`) and `db` (`150Mi`).

That demonstrates:
1) That we don't actually need double our actual usage, because the containers don't necessarily need to get upgraded all at the same time (though that is a slightly scary thought, because sometimes we're publishing changes that depend on each other in different containers
2) Why the deployment eventually worked: when we fixed the hg deployment (I'm guessing @hahn-kev cleaned up the [problematic repo](https://github.com/sillsdev/languageforge-lexbox/pull/704#issue-2231426082)), it was able to complete, thus freeing up another `800Mi`, which was oodles for the `lexbox` deployment to finish rolling out.

It's worth noting at this point that while:
Our staging memory limit is currently only: `2560Mi`
Our production memory limit is a whopping: `6Gi`

At the same time, in production we use a lot more memory. Something like this:
```
   350Mi (api - lexbox)
   100Mi (otel - lexbox)
   150Mi (ui)
  1000Mi (hgweb - hg)
  1000Mi (hgresumable - hg)
   100Mi (db)
   150Mi (db - backup)
+ 1000Mi (snapshots - backup)
-------
= 3850Mi 
```

`3850Mi x 2 > 6Gi`, so in prod, we're also somewhat dependant on rollouts working or else failing deployments could give us memory trouble.

It suggests we should think about backwards compatibility (e.g. how we created symlinks in hg as we transitioned to the new repo structure).

**Comment by hahn-kev** [comment]
For production our backups are a job meaning they only use memory when running and they only run once a day, so our actual normal memory usage is 2850Mi which is under our limit. But I suppose if we were to deploy while a backup was running it would hit our limit.
