### ISSUE TITLE
Playwright in CI is broken

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#709]
The [last deployment to staging](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8612853179) uncovered a few problems in our Playwright CI configuration:

**High Priority**, because it's preventing us from evaluating/getting results from our Playwright tests.

From [this job](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8612853179/job/23603097956):
- [x] The steps "Password protect Playwright traces" and "Upload Playwright results" are both configured to run even though we don't want to run Playwright tests in that job
- [x] "Upload Playwright results" runs even if "Password protect Playwright traces" fails, which is a bit of a security concern (and was likely not introduced by our transition to Node)

From [this job](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8612853179/job/23603098262):
- [x] Playwright tests fail to run with the error: `line 1: pnpm: command not found`
- [x] "Integration tests (.NET)" did not run, because "Playwright setup" failed. The .NET tests should run regardless of whether Playwright has issues.

**Comment by hahn-kev** [comment]
I've opened a PR for this, I fixed the issues related to running on the self hosted runner and the dotnet tests should run even if the playwright tests fail. I didn't do the others, someone else is welcome to pickup my PR to fix the rest of the issues mentioned above.

**Comment by rmunn** [comment]
Discovered that if we want the .NET Send/Receive tests to run, we'll need to upgrade our self-hosted runner to run Ubuntu 22.04, not 20.04. Opened https://github.com/sillsdev/languageforge-lexbox/issues/714 to track that.
