### ISSUE TITLE
Get rid of BOM (U+FEFF) characters in UTF-8 files

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#71]
When running `./setup.sh` on a brand-new repository, I got the following error:

```plaintext
./setup.sh: line 1: ﻿#!/bin/sh: No such file or directory
```

Seems strange, right? Why can't it find `/bin/sh`? I look for it and it's right there.

Well, the answer is that it's not looking for `/bin/sh`, it's looking for `﻿#!/bin/sh`. And it won't find `﻿#!/bin/sh` anywhere on the system. Important note: it's not looking for `#!/bin/sh`, it's looking for `﻿#!/bin/sh`. Can't tell the difference between those two strings of text? There *is* a difference: paste them into https://babelstone.co.uk/Unicode/whatisit.html and you'll see that the second one has a U+FEFF character right before the `#!`. The Unix standard is to look for the characters `#!` at the start of a file to specify what interpreter to use, **not** the characters `<U+FEFF>#!`.

And that last point is a very important detail that things like https://www.unicode.org/faq/utf_bom.html don't mention enough. That FAQ says that "Some byte oriented protocols expect [ASCII](https://www.unicode.org/glossary/#ASCII) characters at the beginning of a file. If [UTF-8](https://www.unicode.org/glossary/#UTF_8) is used with these protocols, use of the BOM as [encoding form](https://www.unicode.org/glossary/#encoding_form) signature should be avoided." What that means, in basic terms, is this:

**Putting a BOM in a UTF-8 file breaks the promise of UTF-8**.

The brilliant part of UTF-8's design is that it is backwards-compatible with older software that expects ASCII. Putting a BOM at the start of a UTF-8 file breaks that backwards-compatibility promise. For this and other reasons (e.g., can't concat two files any more if they have BOM marks, though that's a more infrequent problem), the BOM character should be **avoided** in UTF-8 files, and removed from any UTF-8 files we have in our repo if it's already present.

**Comment by rmunn** [comment]
Other places where a BOM can cause issues is in [robots.txt files](https://www.gsqi.com/marketing-blog/utf-8-bom-robots-txt/). Which we'll want to have eventually. Once we do, we **must** make sure that it, at least, does not contain a BOM.

**Comment by hahn-kev** [comment]
Thanks Robin, this is something I've been meaning to look into. I'm wondering, is there a way to setup git to strip the BOM from files on checkin? similar to how you can configure it to change line endings on checkin/checkout on windows?

**Comment by rmunn** [comment]
Doesn't look like it. Git will configure CR/LF line endings, but not strip BOMs. There's no setting in the Git config that mentions BOMs at all. We'll have to rely on editorconfig files and occasional checks, to find out if anyone has an editor that's not set to honor editorconfig files.

PR incoming.
