### ISSUE TITLE
Request: ability to download two (or more) projects at once

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#718]
Ron Lockwood sent us an email requesting the ability to download (or re-download) multiple FLEx projects at once. He wrote:

> Another aspect of this, especially with regards to FLExTrans is that I want to re-download 2 FLEx projects at the same time. One is the source project and the other is the target. It would be wonderful to do some kind of batch download where I can select all the projects I want to download from the server. I'm frequently downloading 2 projects using the Get project from colleague option. When I switch to a new computer, the batch option would be very helpful to get all the projects I normally work with.

It's not yet clear whether #631 would be adequate for this use case, or whether he wants the ability to run two Send/Receives at the same time (which might need to be done in Chorus or FLExBridge).

**Comment by hahn-kev** [comment]
I'm not actually sure we want to implement anything special for this as it seems like a pretty rare use case, even then it's not clear what benefit there would be.

**Comment by megahirt** [comment]
in our team meeting we talked about maybe making a FLExBridge console app that Ron could then drive in his application, so he could manage pulling projects in his app and queuing, etc.

**Comment by hahn-kev** [comment]
so it sounds like we're not going to take this on? (download multiple projects at once), but we've got some alternative solutions to the issue? Can we close this?
