### ISSUE TITLE
Draft projects are included when filtering projects by member

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#719]
Draft projects should probably just be excluded from the GQL selection.

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/69f294e2-ada1-4c6c-b216-d38ff16e7a6e)

**Comment by rmunn** [comment]
Are we sure we want this? If I'm a LexBox admin and I want to see the projects that tim_haasdyk is a member of, I think I'd also want to see that Tim has requested to create a `foo-test-flex` project. For myself, I'd actually consider it a bug if draft projects were *not* included in the search results.

**Comment by hahn-kev** [comment]
Yeah that's a good point, it does kinda make sense to show those projects.

**Comment by myieye** [comment]
Actually...I wonder if we forgot (?) to make the requesting user a foreign key. Because if it were, it would be super easy to extend the member search to work for draft projects.
