### ISSUE TITLE
Run first Send/Receive test set alone

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#723]
I've merged some of the recent Send/Receive integration test failure logs with hg errors (there were only 2):

```
HG error: 	[12/Apr/2024:13:11:46 +0000] "POST /hg/s/send-new-project-dc75fc2c-dev-flex?cmd=unbundle HTTP/1.1" 500 528
12 Apr 2024 13:11:49 GMT -- abort: stream ended unexpectedly (got 177 bytes, expected 479) -- InvalidPassOnSendReceiveHgWeb -- Ubuntu
12 Apr 2024 13:11:49 GMT -- abort: stream ended unexpectedly  (got 1259842 bytes, expected 1691273) -- CloneBigProject -- Windows
12 Apr 2024 13:11:50 GMT -- but was actually "Sync success: No changes from others -- SendNewProject -- Ubuntu
HG error: 	[Apr 12 13:11:50.080362 2024] [wsgi:info] [pid 1:tid 140115565848448] mod_wsgi (pid=8): Process 'hgweb' terminated by signal 9
12 Apr 2024 13:11:53 GMT -- abort: stream ended unexpectedly (got 324894 bytes, expected 346746) -- CloneBigProject -- Windows


12 Apr 2024 15:43:04 GMT -- Error while copying content to a stream. The response ended prematurely. (ResponseEnded) -- SimpleClone -- Ubuntu

12 Apr 2024 15:51:35 GMT -- but was actually "Sync success: No changes from others -- SendNewProject -- Windows
HG error: 	[12/Apr/2024:15:51:42 +0000] "POST /hg/s/send-new-project-3ed71b38-dev-flex?cmd=unbundle HTTP/1.1" 500 528
			[Apr 12 15:51:42.497877 2024] [wsgi:error] [pid 170:tid 140115305289408] [remote 10.42.5.185:38826] OSError: Apache/mod_wsgi request data read error: Partial results are valid but processing is incomplete.


12 Apr 2024 15:58:49 GMT -- The response ended prematurely, with at least 4050371 additional bytes expected. -- CloneBigProject -- Windows
12 Apr 2024 16:00:43 GMT -- abort: connection ended unexpectedly -- CloneBigProject -- Ubuntu
12 Apr 2024 16:00:44 GMT -- abort: connection ended unexpectedly -- CloneBigProject -- Windows
12 Apr 2024 16:01:09 GMT -- abort: connection ended unexpectedly -- CloneBigProject -- Windows
```

What I think we can glean from this is:
1) `CloneBigProject` and `SendNewProject` (which I've renamed to SendNewProject_Big, so it's more explicit) are the ones that tend to fail. That's almost certainly, because they're big.
2) Even the big tests tend to fail in clumps. Which suggests that the server is overloaded.
3) There's a bit of a domino effect: `InvalidPassOnSendReceiveHgWeb` almost certainly only failed, because of the hgweb error that was presumably caused by 3 other big tests taking out the hgweb process.

The first failure sounds like it could be an OOM kill. We could get more memory. BUT, other tests are likely hitting Cloudflare timeouts and we don't really anticipate staging ever getting a lot faster.

What if we ran a single configuration (e.g. ubuntu-latest + hg 6) FIRST and THEN the other 3 afterwards. That would increase the chances of getting at least 1 green run on a more regular basis.

**Comment by hahn-kev** [comment]
I think if the server is getting overloaded then we should just give it more memory.

**Comment by hahn-kev** [comment]
going to close this unless there's a better reason why we need this
