### ISSUE TITLE
Invalid email in Add/Invite Member results in 500

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#730]
We currently determine whether a value is an email address simply based on whether it has an '@'.
So if a user enters e.g. 'text@' we try to send an invitation email, which blows up in the user's face.
We need to handle or validate invalid emails more gracefully.

[Example trace](https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-api/result/odjJJJz5YRo/trace/2HCECqoS1xG?fields[]=s_serviceName&fields[]=s_name&span=e5ede9d5b172333e)

**Comment by megahirt** [comment]
What does the blow up look like?  An exception when failing to send to the email address?

Email validation is hard.  Don't get bogged down by the details of validation.  https://www.google.com/search?q=email+validation+is+hard

**Comment by myieye** [comment]
@megahirt No, users aren't notified if emails fail to send. We just quietly retry a few times.
The current problem is that we're accepting values that are not parsable as email addresses.
We just need some basic format validation. We already have `zod` and @rmunn is [currently adding](https://github.com/sillsdev/languageforge-lexbox/pull/697/files#diff-87e16c1d250d30b6f69a37e04d020910a951ddbd1aaea4dc401c737dbea6d74dR179) better server-side email validation in bulk-add.

**Comment by megahirt** [comment]
> The current problem is that we're accepting values that are not parsable as email addresses.

So the recommendation is to utilize the existing `zod` library client side, correct?

**Comment by myieye** [comment]
@megahirt Correct. We're already using it on our other email fields. It just wasn't super obvious how to use that validation on "hybrid fields" that can be either a username or an email address.
I've done that now in d630e8c1eab28e045c6a695d1271d2f4e513db42 of the resolving PR.
