### ISSUE TITLE
Allow deleting draft projects 

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#741]
Right now there's no way in the UI to delete a draft project, in some cases we don't want to create it.

**Comment by rmunn** [comment]
Tested on staging, confirmed to work. I registered myself as a non-project creator, and created a project request / draft project. As an admin in another tab, I then deleted the request. Then as the non-project creator user again, I was able to create the project request (with the same project code) again. No problems. I tried several scenarios to make it fail (reusing a project code that belonged to a real project that had been soft-deleted, for example) and it still didn't fail. Everything worked as it should.
