### ISSUE TITLE
Use non root dotnet containers 

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#742]
Right now our API container runs as root, this is no longer required. 

It should be [pretty easy](https://github.com/dotnet/dotnet-docker/blob/e5e8164460037e77902cd269c788eccbdeea5edd/samples/dotnetapp/Dockerfile#L20), but we will need to test our permission issues, mostly creating new repos.

**Comment by rmunn** [comment]
We'll definitely want to run as UID 33 (www-data) so that permissions on newly-created repos will be correct when the hgweb container mounts the same volume.

**Comment by rmunn** [comment]
#745 is the naive implementation. I suspect it'll fail in local dev because `dotnet watch` will need to rebuild DLLs that ended up owned by root in the previous build steps, but let's give the naive implementation a try; maybe it'll surprise us.
