### ISSUE TITLE
New manager does not have permission to create projects

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#751]
When a project request is fulfilled by an admin, the assigned manager is not granted the `CanCreateProjects` permission.

Example user: https://languagedepot.org/admin?userSearch=df2c8208-b484-47f5-805e-0b0bbbb22af5

**Comment by rmunn** [comment]
Confirmed to be working on staging. I created a non-admin account for myself, and requested one project. I then (as admin in another tab) approved it and created it. My non-admin account had to log out and log back in to register the change to my permissions, but after I logged out and logged back in, my second project was created directly without needing to request it.

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/90762/b4b235a1-8c09-473e-9445-4c0b5e85ff36)
