### ISSUE TITLE
Metadata is not cleared/reset when a repo is left empty or is in the middle of a reset

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#756]

**Comment by rmunn** [comment]
I believe this has been fixed by #740, specifically in commit https://github.com/sillsdev/languageforge-lexbox/pull/740/commits/d8594a1549f274dd9d67859ca2777be4207ceffb. Closing as fixed.

**Comment by rmunn** [comment]
Tested on staging, confirmed that the last commit date is reset to null and LexEntryCount (if applicable) is reset to either null or 0 when a project is left empty.

I did discover that after a .zip file is uploaded in FinishReset, the lex entry count still remains 0, so perhaps the UpdateProjectMetadata task is running too soon and needs to be moved to a job. I'll open a new issue for that minor problem.
