### ISSUE TITLE
Speed up local dev setup by downloading repo zips beforehand

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#758]
I often end up running `skaffold delete` for a variety of reasons. When I do, everything including the `hg-repos` volume gets deleted. After that, it has to download our 700-megabyte test repo from Google Drive again, which means at least a minute or two, sometimes ten, before I can get my local LexBox installation back up and running.

Our Taskfile.yml already has a `setup` task that downloads sena-3 and unzips it to hgweb/repos. I'd like us to add a step that would also download the other large test repo we use, as well. Perhaps we wouldn't unzip this one, but leave it as a .zip file.

Then, in order to get that data into Kubernetes, the populate-test-repos script in local-dev could mount a [hostPath volume](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) to /init-repos. If the repo exists in /init-repos, it's copied/unzipped without redownloading it; if it doesn't exist, then it's redownloaded as per the current behavior.

We wouldn't want to check a 700-megabyte file into our Git repo, but by putting the download into `task setup` (and adding the corresponding .zip filename to .gitignore to make sure nobody checks it in by mistake) we could save ourselves some time whenever we need to run `skaffold delete` and reinstall LexBox from scratch again.

**Comment by rmunn** [comment]
I might be the only one who wants this, so this is probably low-priority. But it would make my life easier to be able to pre-populate the hg-repos volume from my existing data. From what I can tell by looking at how the Taskfile.yml is set up, this used to work when we were running with docker compose (because docker compose pre-populates volumes from the contents of a directory) but in Kubernetes, you don't get pre-populated volumes.

It might also be nice to adjust the populate-test-repos script to copy *any* repos found in the hostPath volume, so that it would be easy for me to grab a dozen test repos, for testing a variety of Send/Receive scenarios, and have them around all the time.

**Comment by rmunn** [comment]
I don't think this can be done. I can create a local directory with `sena-3.zip` in it, and define a Kubernetes `hostPath` volume pointing to the directory, but the sena-3.zip file doesn't get loaded into the Kubernetes volume. After quite a lot of time spent digging, I learned that under Docker Desktop the host path that Kubernetes sees is from the docker-desktop VM, not your actual host system. And while you can apparently bind-mount host files into the docker-desktop VM, you can't control the path inside the VM, and that path will be **different under Linux and Windows**. I have not been able to find where the path ends up under Linux, but multiple sources say that under Windows, it will be something like `/run/desktop/mnt/host/wsl/path/to/file` or `/run/desktop/mnt/host/c/path/to/file`.

Which means that I cannot create a Kubernetes `hostPath` config that will work on both Linux and Windows dev machines. (You cannot use relative paths in `hostPath`, only absolute paths are allowed). Which means I cannot do this.

**SIGH**. Why is it so difficult to pre-populate a Kubernetes volume with a file that you have right there on your local hard drive? I could use a ConfigMap, but since the file is 700 megabytes that seems more than a little silly (it will be base64-encoded).

Giving up on this idea.

**Comment by rmunn** [comment]
Reopening as I've had an idea that might fix this.

First, I've found a Docker Desktop for Linux issue that suggests the mount point is `/host_mnt` inside the VM. So to access a folder called `/lexbox-data` on your host, you'd access `/host_mnt/lexbox-data` in the k8s YAML.

Second, we could create a `task setup` subtask that would do a search-and-replace on the k8s YAML, replacing `$HOSTMOUNT` with `/host_mnt` on Linux and `/run/desktop/mnt/host/c` on Windows. This breaks with the Kubernetes design philosophy of never allowing environment variables or template variables in k8s YAML files, but since their design philosophy is **wrong** in this instance, I don't mind breaking with it. It's only on local dev anyway.

**Comment by hahn-kev** [comment]
rather than modifying some yaml files it would probably make more sense to use the local.env file we already have, then use that to generate a config which we can use a [kustomzie replacement](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#example) to copy the value from a config to the pvc. There's a few hoops to jump though. 

On the other hand it might be simpler to allow changing the URL that the files are downloaded from, then just have a server locally serve those files. Either that or somehow pull the pvc out of the delete, so it persists between skaffold deletes.

**Comment by rmunn** [comment]
Another idea would be to keep the files around after `task setup` downloads them, putting the folder they're in into `.gitignore` so it won't be accidentally checked in. Then we could create a Dockerfile that builds those files right into the image, so that when the Kubernetes pod starts up the files are there already before any volume is mounted. Then the pod can just copy the files into the volume and not have to download them at startup time.

**Comment by hahn-kev** [comment]
Yeah that would work pretty well actually. For the matter just download them as part of the docker build, it'll be cached so it'll only happen once. We will need to make sure that only happens in local dev, as it doesn't make much sense to do that in staging or develop considering it's rarely reset.
