### ISSUE TITLE
After uploading a .zip file in project reset, LexEntryCount incorrecly remains 0

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#765]
After resetting a project (on staging, on 2024-04-29), the LexEntryCount was set to 0 while the project was empty, which is correct. But after uploading a .zip file, the LexEntryCount remained 0 until I clicked the refresh button next to it, which then correctly set the entry count to 1,462. Only LexBox admins have access to that refresh button, so project managers wouldn't be able to fix the issue.

![image](https://github.com/sillsdev/languageforge-lexbox/assets/90762/3320edf6-f558-4561-9a8f-1bd3cf1e0246)

One easy solution would be to say "Hey, we know the lex entry count works now, so let's let project managers click the reset button as well". Another would be to fix the underlying issue, which is that the new lex entry count is being requested too soon after the new project is put into place, so Mercurial (for whatever reason) is trying to read the lex entry count from what it still thinks is an empty repo:

```plaintext
Linguistics/Lexicon/Lexicon_01.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_02.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_03.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_04.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_05.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_06.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_07.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_08.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_09.lexdb: no such file in rev 000000000000
Linguistics/Lexicon/Lexicon_10.lexdb: no such file in rev 000000000000
10.1.4.207 - - [29/Apr/2024:06:25:59 +0000] "GET /command/sena-3/lexentrycount HTTP/1.1" 200 2
```

**Comment by rmunn** [comment]
Not managing to reproduce on local dev. Might be timing dependent.

On staging, I just saw the following error go past when the lexentrycount command was attempted: `chg: abort: cannot open cwd (errno = 116, Stale file handle)`. Perhaps I can catch that condition and have it retry? "Stale file handle" means that the current working directory for the process was in the directory that was just deleted, rather than the one that was moved into place. I don't know why that would be, because the lexentrycount code is running after `await FinishReset`, so by the time the FinishReset task returns, the Directory.MoveTo method *should* have finished running. Unless there's something about Task concurrency I don't understand yet.

**Comment by rmunn** [comment]
There's definitely some caching going on at the filesystem level that's affecting this. If I edit the command-runner.sh script on staging and add `ls /var/hg/repos/$first_char/$project_code/ >/dev/null` right before the `cd /var/hg/repos/$first_char/$project_code/` line, suddenly everything works as it should.

Talking it over with Tim Eves, he believes it's NFS caching the file descriptor for the repo directory. Moving the empty repo directory away, then moving the new directory into place, is resulting in NFS not realizing that its cache for `/var/hg/repos/$first_char/$project_code/` is out of date (for reasons I have yet to determine), and so any code that has done an `opendir` stat call to get a file handle for that directory, will still have the stale file handle that NFS has given it. But if you do an `ls`, that (among other things) does an opendir and a closedir, which makes NFS realize that its cache is stale.

So if we have FinishReset run a `Directory.GetFiles` right before returning, that might be enough to bypass this issue. Tomorrow I'll create a PR to that effect, since I'm running out of time in my working day today.

**Comment by myieye** [comment]
@rmunn I just want you to know that I feel like this could be a BIG find and I'm excited about figuring it out and getting it right! Thanks for working on it!

**Comment by myieye** [comment]
- [ ] I've added some `// TODO 765` comments necessary to get some tests green again

**Comment by hahn-kev** [comment]
That's very interesting, I wonder if this effects hgweb directly and might account for similar issues that we attributed to the `refreshinterval` but is actually something lower level. If `Directory.GetFiles` busts up the cache then we could do that after we init a new repo also and maybe solve other issues?

**Comment by rmunn** [comment]
See https://stackoverflow.com/a/30630912 for more details on that `opendir`/`closedir` thing as it relates to NFS.

**Comment by rmunn** [comment]
A bit of testing with the `ltrace` and `strace` tool (on my local dev box) shows that calling `Directory.GetFiles` does *not* call the C library's `opendir` and `closedir` functions; rather it calls the `openat` syscall from the Linux kernel.

I do not yet have evidence to show, one way or the other, whether `openat` will cause NFS to invalidate its directory cache, or whether the C `opendir` and `closedir` functions are what NFS uses to realize that its directory cache is out-of-date. I'll figure out a way to test that on staging and report my findings.

**Comment by rmunn** [comment]
Can't reproduce on staging right now, so having trouble proving whether `Directory.GetFiles` or `ls` would be enough.

**Comment by myieye** [comment]
What if we just add a call to `Directory.GetFiles` after resetting the repo and see if that seems to fix the Playwright tests?
The Playwright tests fail quite consistently. So, I think that would be a decent test for the fix.

**Comment by rmunn** [comment]
@myieye - Okay, I've done that in #789. Let's see what that does.
