### ISSUE TITLE
Can't delete projects in develop

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#770]
- [x] Trying to delete a project in develop results in a 500. ([trace](https://ui.honeycomb.io/sil-language-forge/environments/develop/trace/kq5GZKRsL1W?fields[]=s_name&fields[]=s_serviceName&span=bada01e9ceb60c0b))

```
exception.message
Access to the path '/hg-repos/_____deleted_____' is denied.
```

I assume this was caused by #742.

Run `chown -R www-data:www-data /var/hg/repos` after next deployment in:
- [ ] staging
- [ ] prod

#783 (turned out to be a different issue)

**Comment by rmunn** [comment]
Definitely caused by `_____deleted_____` being owned by root rather than www-data. We'll want to add a script that runs `chmod -R www-data:www-data /var/hg/repos`. But NOT as an init container (or if an init container, then only run it once and then STOP running it in the future), because `chmod -R` has to recursively descend through the whole volume and that will take several minutes in production. After we switch production over to the non-root container, we should never end up with files owned by root anymore, so paying the several-minute cost of `chmod -R` every time we deploy would be counterproductive.

So I suggest a script that is NOT an initContainer. We run it once before deploying the non-root lexbox container, then run it again immediately after deploying the non-root container in order to catch any files that might have been created in the past few minutes. Then it should never need to be run again.

**Comment by rmunn** [comment]
I've run the `chown` command above on develop, so this should now be solved on develop. (Sure enough, `_____deleted_____` and `_____temp_____` were owned by root. Interestingly, so was /var/hg/repos/s but no other single-character dirs.) However, I will leave this issue open because there are going to be more problems caused by this change in the future.

**Comment by myieye** [comment]
So, I ran the command (`chown -R www-data:www-data /var/hg/repos`) in staging, even though it looks like everything was already www-data:www-data 🤷.

**Comment by myieye** [comment]
The theory is that it might make sense to run the command after deploying to catch any left overs.
So, I'm going to leave this issue open until it reaches the Done column.

**Comment by rmunn** [comment]
I don't know what happened, but /var/hg/repos on staging currently (2024-05-07 09:33 UTC) has a `_____deleted_____` folder that's *entirely* owned by root. Except for one single deleted project, sena-3__2024-02-16T12-48-33__reset, which is owned by www-data. I'm about to run the `chown -R` command on staging.

**Comment by myieye** [comment]
So, looking at all of this again:

### Even though @rmunn set the ownership of everything last week ☝. There are currently a few repos that are owned by root:

![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/e89e8956-87a5-4c07-9de7-041809f96aa1)

That doesn't cause problems atm, beacuse the group has read and write permission on the repo directories. But apparently the `_____deleted_____` directory was owned by root and that **would** cause problems because the group currently does **not** have write access to the deleted and temp directories.

And we don't know **why** root is getting ownership of the directories

### With that said, it seems we've actually been ok so far.

We haven't had any errors on develop since @rmunn [changed the ownership](https://github.com/sillsdev/languageforge-lexbox/issues/770#issuecomment-2095569214) there.

([graph](https://ui.honeycomb.io/sil-language-forge/environments/develop?query=%7B%22start_time%22%3A1713817084%2C%22end_time%22%3A1715324435%2C%22granularity%22%3A0%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22exception.message%22%2C%22op%22%3A%22contains%22%2C%22value%22%3A%22denied%22%7D%5D%2C%22filter_combination%22%3A%22OR%22%2C%22limit%22%3A100%7D), [last occurence](https://ui.honeycomb.io/sil-language-forge/environments/develop/result/b8vRbzuV1kM/trace/aPbResLGfHY?fields[]=s_name&fields[]=s_serviceName&source=query_se&span=399b2c11a46e7025))
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/92860846-fd81-4e61-aba0-c5c201a75f1e)

And we've **never** had errors on staging:
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/eb78eb78-3222-4e9e-8250-bd267b24ae09)

### So, I almost feel comfortable deploying to prod

But, maybe we should give the www-data group write permission on all of the root directores (deleted, temp, a-z etc.)?
@rmunn , @hahn-kev does that make sense?

**Comment by hahn-kev** [comment]
Yeah that sounds good to me 👍

**Comment by myieye** [comment]
I just realized that the owner and group of the volume-root is always root.
That means, for new deployments of Lexbox, .NET would fail to create the deleted and temp repo directories.
The reason seems to be that [`fsGroup` doesn't work for NFS mounts](https://github.com/kubernetes/examples/issues/260).

So, here's what I think we should do:
- Use an initContainer for hg and lexbox pods to set the group of the volume-root to www-data
- Move the init-repo-structure stuff into .NET, because it seems weird to me that .NET assumes the a-z etc. directories exist, but that it needs to create the deleted/temp directories itself.
- Use our current permission logic in .NET to set the permissions of all of those directories.
  - @hahn-kev I'm not sure when. Should this be static initialization code or do we run it whenever a repo gets [re-]initialized? I think I just learned that `Directory.CreateDirectory(path)` implicitly creates all necessary sub directories, but `DirectoryInfo.Create()` does not. But, if we want to explicitly set permissions on the a-z directories, we'll probably need to make their creation more explicit as well.
- That won't work if any of those directories already exist and are owned by root. So, I'd use the initContainer to also set the owner, group and permissions of any existing directories.

**Comment by hahn-kev** [comment]
man, fsGroup I feel like is always disappointing.

That sounds good, I'm not sure we need an init container on both hg and lexbox pods as they would both be writing to the same location (the hg repos volume). I agree we should create the a-z dirs, as for where I think we can setup a background job/worker to do that (deleted folder included) and then if there's an error creating those dirs then the server won't startup, then our code can assume they exist no problem.

**Comment by rmunn** [comment]
Drawing from experience with Language Forge, we want our initContainer to run fast. That means that we want to avoid doing a `chown -R` step on the repositories. We did that at one point with our `lfmerge` container and it actually took several minutes to complete as it descended through tens of thousands of files. Doing `chown` on the root of the volume is safe, though, as is doing `chown www-data:www-data /var/hg/repos/*` to ensure the top-level folders are all owned by www-data. I'd recommend against running `chown www-data:www-data /var/hg/repos/*/*` in the initContainer, though, as that could potentially need to look at thousands of files and would make the initContainer a lot slower than it needs to be.

I don't quite agree with moving init-repo-structure work into .NET; rather, I'd like the initContainer to create the `_____deleted_____` and `_____temp_____` directories in addition to the other ones (and run `chown` after creating them, as previously mentioned). Then .NET can assume they exist, which will simplify the code a little.
