### ISSUE TITLE
running task setup for first time shows `rm: cannot find path` error

### ISSUE THREAD

**Issue by megahirt** [sillsdev/languageforge-lexbox#773]
when following the developer instructions for the first time, I see an error message when I run `task setup`:
```
PS C:\src> cd .\languageforge-lexbox\
PS C:\src\languageforge-lexbox> task setup
[setup-win] rm : Cannot find path 'C:\src\languageforge-lexbox\hgweb\repos\sena-3' because it does not exist.
[setup-win] At line:1 char:1
[setup-win] + rm -r ./hgweb/repos/sena-3
[setup-win] + ~~~~~~~~~~~~~~~~~~~~~~~~~~
[setup-win]     + CategoryInfo          : ObjectNotFound: (C:\src\language...eb\repos\sena-3:String) [Remove-Item], ItemNotFoundEx
[setup-win]    ception
[setup-win]     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
[setup-win]
```

This is not a problem because `task setup` goes ahead and downloads sena-3 in the next line.  This just looks ugly and could potentially appear like a legit problem on setup.  I hesitated to even create an issue for this, but...

**Comment by rmunn** [comment]
Easily solved by converting `rm -r` to `rm -rf`. The `-f` option to `rm` means "ignore nonexistent files and arguments, never prompt".

**Comment by rmunn** [comment]
It seems the PowerShell `-Force` option does not allow it to ignore nonexistent files: https://stackoverflow.com/questions/63157509/rm-f-equivalent-for-powershell-that-ignore-nonexistent-files

Proposed solution from that SO accepted answer is:

```powershell
if (test-path $file) {
  remove-item $file
}
```

which we would, of course, add `-r` to.
