### ISSUE TITLE
Allow listing orgs

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#776]
First design ideas:

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/23c2fe76-0350-4706-88e0-a69970bebe30)
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/6fd2ee7c-87f5-4e49-aac5-6f526a3af777)

Orgs table has:
- Name. Clicking goes to Org page #779
- Users (count of users)
- Created
- ~Actions for filtering users and eventually projects by org~ Just click on the org to see users and projects

User table is extended with action:
- Filter orgs

**Comment by hahn-kev** [comment]
We do want to expose the list of all orgs to all users, so we may want to take that into consideration here. We could very well break out into 2 issues, one for admins and one for users.

**Comment by rmunn** [comment]
I wrote in the description for #837 that filtering and sorting is coming next, but perhaps improving the formatting of the org list should wait until more parts of orgs are implemented? Perhaps I'll leave filtering and sorting for a later date, and work on admins being able to create orgs and manage org membership next. Then we'll have a more complete, if still barebones-looking from a UI perspective, set of tools for managing orgs. Once admins can add and remove users as org members, then I think it will be time to polish up the UI with things like sorting, filtering, and paging.
