### ISSUE TITLE
Org page

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#779]
We need an Org page, just like our project page. It shows:
- [ ] Name
- [ ] Members

And it's the workspace for org admins to:
- [ ] add members
- [ ] set member roles.

Permissions:
- Org admins
  - member CRUD (for now they will be auto added, but we may want that to be an invite process in the future)
- Org members
  - view member list
- Non org members
  - view org
  - list admins (including email tbd?), not other members

I assume we'll want the same member workflows we currently use for adding members to projects and setting their roles.

I think it would be very easy and reasonable to share a component with the project page for the general layout:
- Header
- Badges (Not sure what might go here for orgs)
- Attributes (description)
- History (eventually)
- More settings (delete, leave etc.)

Some minimal, but distinct style/color differences would be wonderful, so that the project page and org page can't be confused. And maybe so that the org page feels a tad "fancy", fresh and desirable.

Adding a project list to the org page is tracked in #788

**Comment by rmunn** [comment]
This seems like the first one to start with; once the org page exists, then creating and listing orgs would be the next steps.
