### ISSUE TITLE
Can't access hg pod in develop

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#783]
Accessing hg in develop is/was not working.

The problem turned out to be the namespace selector in [the new NetworkPolicy](https://github.com/sillsdev/languageforge-lexbox/pull/752).
It seems, the name stayed `languagedepot` instead of getting mapped to `languagedepot-dev` [as predicted](https://github.com/sillsdev/languageforge-lexbox/pull/752#pullrequestreview-2021101159).

When I added `-dev` things started working again (e.g. loading changesets).
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/6b4a8a32-cc52-4322-a50c-75a7288d85d6)

@hahn-kev do you know what to do about this/where to look?

**Comment by hahn-kev** [comment]
Oh that's very interesting, I have no idea. @tim-eves do you have a suggestion? basically our network policy uses the namespace as a match, but that name isn't getting transformed by rancher fleet the way that the resource namespaces are. This is not currently being handled by kustomize as the deploy repos still references the languagedepot namespace, only fleet is responsible for transforming the namespace. Do you have a suggestion for how we can fix this?

**Comment by rmunn** [comment]
One fix we could implement right away is to adjust that NetworkPolicy to allow access from either the `languagedepot` *or* `languagedepot-dev` namespaces.
