### ISSUE TITLE
Link projects to an org

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#788]
projects should optionally (for now at least) be able to be under a project. From the frontend this will be a one to many relationship. A project can only be part of one org. However on the backend we don't want to trap ourselves into a corner in case we want to open that up in the future, this is to let us follow paratext and have a project be owned by multiple orgs.

This will require a few things

- [x] add linking table in db
- [x] add apis for adding and removing
- [x] list projects on org page
- [x] #905
- [x] #906
- [x] update permissions so that org members can view (in the UI) projects owned by their org when the project is not confidential (unknown is also hidden) - part of #888
- [x] #915

We can break these out into sub issues as needed.

**Comment by rmunn** [comment]
For adding and removing projects from an org, I chose to require the person doing so to have edit permissions on the *organization* rather than on the *project*. If it should be the other way around (project managers can add project to any org), it'll be quite easy to change the code.

Alternately, we could set it so someone who is *either* a project manager *or* an org admin can assign that project to the org. (We clearly don't want an "and", as there will be basically zero people who are both project managers *and* org admins). Discussion needed?

**Comment by hahn-kev** [comment]
actually to start I think onboarding will be for people who manage many projects (like Scott D) already and they want to consolidate them under an org, they will be an org admin and the manager of the project so they should be able to add the project to the org.

**Comment by rmunn** [comment]
@hahn-kev - What I think you're saying that the restriction should be "To add a project to an org, you must be an org admin *and* a manager of that project." Do I have that right?

**Comment by hahn-kev** [comment]
Yes that's right, it's a bit restrictive, but we can adjust it as needed if we deem that necessary later on. We might even let a manager add their project to any org. But for now let's require both.

**Comment by megahirt** [comment]
Also, "if you are a super admin"...then you can add a project to an org.

Chris

**Comment by myieye** [comment]
I would think that the requirement for adding a project to an org/or removing it would be:
- You manage the project (or are a super admin) and
- You're a member of the org (or are a super admin)

That's how it will presumably work when you create a project:
- You'll become the manager of the project
- You'll pick one of the orgs that you're a member of and it'll be added to that one

So, @hahn-kev why would you restrict it to org admins at the beginning?
I think org admins control what projects are in their org by controlling who is a member of the org.
