### ISSUE TITLE
Idea: Admin dashboard filter for "users I created"

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#810]
We should add a user filter for "user accounts I created". The URL query param could be `createdBy=email@example.com`. That would be useful for certain scenarios, like removing guest user accounts after a workshop. Usually a workshop would involve just one project, so you could find them via the project, but it's entirely possible you might have multiple projects during a large workshop and then you might not remember all the usernames you created. It might be hard to find them all in the users table containing hundreds of accounts, but if you can filter to just the ones you created, that would probably make it much easier.

**Comment by hahn-kev** [comment]
while we're at it we should surface who the user was created by, at the very least in the details dialog.

**Comment by rmunn** [comment]
Now that implementation has started, I'm realizing that the query parameter `createdBy=email@example.com` is less useful than `createdById=some-guid`. The latter would make the implementation simpler.

**Comment by rmunn** [comment]
> while we're at it we should surface who the user was created by, at the very least in the details dialog.

We decided not to include this in PR https://github.com/sillsdev/languageforge-lexbox/pull/895, so we created https://github.com/sillsdev/languageforge-lexbox/issues/897 to track this idea for a future PR.
