### ISSUE TITLE
error thrown when trying to promote guest user to admin

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#813]
guest user being a user without an email, created via an admin or bulk add. Right now we throw a big ugly error message when they try to promote a user to an admin, we should prevent them from submitting on the frontend with an error why they can't promote the user.

**Comment by rmunn** [comment]
The logic we want the "Edit User" modal to apply on the admin dashboard:

- If email address is null (or undefined or empty) *and* the role dropdown is admin, disable the Submit button.
- Also display an error message under the role field explaining that admins must have a valid email address. (And so guest users can't be promoted to site admin.)

Note that to check if the email address is null or undefined or empty, checking that it is "[falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)" is enough; i.e. `if (!email) { ... }`
