### ISSUE TITLE
warning in dev about missing turnstile property on CreateUserDialog

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#816]
_Originally posted by @hahn-kev in https://github.com/sillsdev/languageforge-lexbox/pull/736#discussion_r1608639347_

we don't want to ignore this warning. 2 solutions that I liked were to either create a component that is specifically for switching turnstile off and on. Or just making it part of Form and making it optional.

**Comment by rmunn** [comment]
Discussed this with Tim at our last meeting and settled on making the MaybeProtectedForm component. This won't take long; PR coming soon.
