### ISSUE TITLE
deleting a draft project does not refresh the project list

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#838]
on the admin page the project list is not refreshed automatically when a draft is deleted

**Comment by rmunn** [comment]
I probably forgot to invalidate the appropriate GraphQL cache. I'll tackle this as it should be a very straightforward fix.

**Comment by rmunn** [comment]
Yep. that was the issue. https://github.com/sillsdev/languageforge-lexbox/pull/840
