### ISSUE TITLE
README needs to mention `git clone --recurse-submodules`

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#848]
Now that we're using submodules, the README.md file needs to mention the need to run `git clone --recurse-submodules` when checking out the repository, otherwise `task up` fails because the Crdt classes can't be found.

The README should also mention that existing repos that were cloned without `--recurse-submodules` need to run `git submodule init` followed by `git submodule update --recursive`.

**Comment by hahn-kev** [comment]
You know it would probably be easier to just run those submodule commands as part of `task setup`
