### ISSUE TITLE
define semantic domain type in CRDTs

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#852]
Semantic domains will consist of (at least) 2 fields.

- index (eg 2.1.1, or 7.2.1.1.1)
- label, multi text, (eg Head, or Run)
- predefined/readonly, indicates that this was a predefined domain and can not be deleted and the index can not be edited.

in FLEx there are more fields, for questions and such, not worried about those for now.

I would recommend starting by just creating the new type, and the changes to create and edit the domains. Then creating some automated tests for those functions, possibly including determining the hierarchy based on the index.

Once it's fully defined, then I would modify the field on Sense to be a reference (or references). A custom change should be defined for modifying this reference as the json patch method will not work as it would allow invalid references. We might just let the UI author it as a json patch, and in the server side pull that patch out into it's own change, but I'm not sure what will work best there.

Side note, somewhere in the code base we will want to define all the domains so they are pre populated in the database. This should be done as a single commit with a hardcoded GUID, this will ensure that we can't end up with duplicate domains by accidentally pre populating the domain list twice.

**Comment by rmunn** [comment]
There's [an XML file in liblcm](https://github.com/sillsdev/liblcm/blob/master/src/SIL.LCModel/Templates/SemDom.xml) that defines the canonical list of semantic domains, with canonical hardcoded GUIDs. We should use that list, whether via a Git submodule or by simply copying the file (it hardly ever changes, so if there's a change we can just copy the change).
