### ISSUE TITLE
define parts of speech types in CRDTs

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#853]
very similar to #852 but for parts of speech.

**Comment by rmunn** [comment]
LibLcm has two XML files, [POS.xml](https://github.com/sillsdev/liblcm/blob/master/src/SIL.LCModel/Templates/POS.xml) that defines the basic parts of speech that all language projects start with, and [GOLDEtic.xml](https://github.com/sillsdev/liblcm/blob/master/src/SIL.LCModel/Templates/GOLDEtic.xml) that defines the hardcoded GUIDs that should be used for all "standard" parts of speech (i.e., when you want to add a new part of speech to a FieldWorks project, you don't get to create one, you have to choose from the standard list that's populated from GOLDEtic.xml — and when you do, you get the hardcoded GUID assigned to that specific part of speech).

As with semantic domains, we should base our parts-of-speech list on those files, using the same GUIDs (and names and descriptions) defined there.

**Comment by rmunn** [comment]
Also as with semantic domains, we should either use a Git submodule or just copy those files into our repo, as they almost never change (last change to either one was in 2020, and that was a change to the English-language definition of one part of speech).
