### ISSUE TITLE
create about page for lexbox

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#854]
should talk about what it's for, what software uses it, and the nature of our relationship to Payap.

**Comment by rmunn** [comment]
@psh0078 - Go ahead and create the page with placeholder content; we'll write the actual content, but I'd like you to create the page with the URL `/about`. It should be reachable by everyone, whether logged in or not, and should use the same basic layout as the rest of the LexBox pages.

**Comment by rmunn** [comment]
#859 just had placeholder content. @psh0078 linked it to this issue at my suggestion, because I wanted him to see how auto-closing issues works. But this issue is not *actually* fixed yet since we still need to populate the About page (which we will do in a separate PR), so I'm reopening it.

**Comment by megahirt** [comment]
Maybe we can do the content authoring as a GitHub wiki page in markdown and then create a PR to publish the content as a separate step

**Comment by hahn-kev** [comment]
That's a good idea, I'm just not sure about how to handle images and such. Do we just reference them from GitHub? Or do we copy them in to the app so it gets deployed? I'd rather deploy the images when the app so the page doesn't have an odd dependency outside of the service.

**Comment by megahirt** [comment]
yeah, I agree images should be hosted by our own service.  Maybe `/frontend/static/images/about` ?
