### ISSUE TITLE
Add VS Code setting for default .sln file

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#857]
Now that there are two ,sln files in the project (LexBox.sln and backend/harmony/harmony.sln), VS Code asks you to choose a default. We should update the .vscode/settings.json file in the project to make LexBox.sln the default solution file when opening the lexbox repo's root dir in VS Code.

**Comment by hahn-kev** [comment]
For minor stuff like this, especially DX stuff that doesn't effect the build, just make a PR, you don't need to make an issue just to make a PR
