### ISSUE TITLE
Show draft projects (if any) on user's home page

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#864]
This will be part of solving https://github.com/sillsdev/languageforge-lexbox/issues/855.

The home page currently shows the projects that the logged-in user is a member of. We want to extend that to show draft projects as well, with a "draft-project" CSS class applied so that we can style them differently. For now, that CSS class will just apply `border: thick double red;` but in the future it will do more. (In LexBox, a "draft project" is what gets created when a user submits a project-creation request but doesn't have project-creation rights. Once an admin approves the project-creation request, the draft project is deleted and a "real" project is created with the same GUID and project code.)

To implement this, you'll need to do several things:

- Look in `backend/LexBoxApi/GraphQL/LexQueries.cs` for the MyProjects query, and create a similar one called MyDraftProjects which will return a list of DraftProject entities rather than Project entities.
    - **Note**: Draft projects do not have a list of members, so the Where clause involving the `Users` property will be different; for draft projects, there is a single project manager assigned. A draft project should appear in a user's homepage only if that user is the assigned project manager.
- In `frontend/src/routes/(authenticated)/+page.ts`, you'll need to add a GraphQL query to fetch any draft projects the user owns, and return that list in a new `draftProjects` property from the `load` function.
- In `frontend/src/routes/(authenticated)/+page.svelte`, you'll need to show draft projects (if any) **before** the list of "real" projects.

Eventually, the list of draft projects on a user's home page will allow the user to click on any draft project to delete it (thereby cancelling the project-creation request), but that is out of scope for this task. For now, just ensure that any draft projects appear in the user's home page, at the start of the list, apply a "draft-project" CSS class to them, and make that CSS class create a red double border around the draft project's visual representation.

**Comment by rmunn** [comment]
We have a code-generation system set up for GraphQL, that allows it to be type-checked in Svelte code. After you make any changes to GraphQL queries or mutations in C#, you should run `task api:generate-gql-schema`. This will recreate the auto-generated `frontend/schema.graphql` file, which is used for type-checking the GraphQL code in Svelte. When you commit your C# changes, make sure you also commit the changes to `frontend/schema.graphql` in the same commit.

Whenever you edit any GraphQL query, you'll notice that the entire query immediately gets a red wavy line underneath the entire thing, indicating a type error. That's because one of the things the type-checking system does is store the *string values* of GraphQL queries, and the one you just edited (or created) no longer matches the string that was stored in the type-checking system. To fix that, cd into the `frontend` directory and run `pnpm build`. (You can also run `task ui:build` from the root directory, but doing it via pnpm gives nicer color output). Once you run `pnpm build`, your GraphQL queries should no longer show red wavy lines throughout. (Unless you've actually made an error, such as requesting a property that doesn't exist, e.g. requesting the `users` property on a `draftProjects` query would be an error).

P.S. In GraphQL terminology, a "query" is a request that does not modify data, similar to an SQL SELECT statement. A "mutation" is something that does modify data, similar to an SQL UPDATE statement. Note that in GraphQL, **both queries and mutations will return data**; typically, we set up mutations to return a copy of the data they just modified, which allows the client-side GraphQL cache to be automatically updated.

**Comment by megahirt** [comment]
Some design ideas:
- make the card and text elements muted / greyed out
- add the text "requested on [date]" or simply "requested"
- another text idea: "requested on [date] and waiting for approval"

**Comment by myieye** [comment]
I like these clock icons 🤓 
But there are lots of tempting icons 😆 

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/4c34d9a8-cd91-4d5e-b706-f85e645f35c1)
https://icon-sets.iconify.design/mdi/clock-check-outline/

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/192a1cc3-23ad-4001-b51b-bdc6aaf66023)
https://icon-sets.iconify.design/mdi/progress-clock/


#### Or

If we replaced all the draft icons with something like this (none of us love the current icon, but it's just challenging to pick a great one):
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/cc333e47-4929-4a44-ae3a-afce76968b91)
https://icon-sets.iconify.design/mdi/receipt-text-clock-outline/

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/2bab8613-1462-4c10-8c13-31a8a5d7a2c8)
https://icon-sets.iconify.design/mdi/book-clock-outline/

...then we don't really need another clock icon and it might look nicer to put "awaiting review" in a little badge:

Something like this (the orange/warning border is optional, but it's kind of cool 🤷  ):
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/77511d32-1191-4acf-9084-153e17cc7c99)

**Comment by hahn-kev** [comment]
I like the mockup Tim made. 

FYI we already have a draft icon on the admin page, so whatever we end up doing should be consistent with that. I think the current icon makes sense, so I'd vote for that one.

**Comment by megahirt** [comment]
In @myieye 's mockup, there is no draft icon after the title name.  Did you decide to drop that intentionally?

I also like having a clock icon next to the text "awaiting approval".

**Comment by myieye** [comment]
@megahirt Sorry for the confusion. No, I didn't leave the icon or anything else out intentionally. I was just trying to demonstrate the badge idea. I should have made that more explicit.

Regarding the draft icon.
What we currently have is this: ([scroll](https://icon-sets.iconify.design/mdi/scroll/))
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/a634031a-7b98-45ad-9b76-e1449b8f7624)

Personally, I don't feel like it communicates very much.

I think this: ([receipt-text-clock-outline/](https://icon-sets.iconify.design/mdi/receipt-text-clock-outline/))
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/69b17b1a-4ff4-41ff-8faf-88a9db7e0c6b)
1) Looks more like a ticket that's been submitted
2) Explicitly communicates waiting (for approval)

That's all the cents I've got.
I think team CNX should just take it from here.

**Comment by rmunn** [comment]
I agree that the scroll isn't great (I didn't want to spend hours searching at the time), and receipt-text-clock-outline is better.
