### ISSUE TITLE
Email notifications for Approved requests and Getting added to a project

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#867]
Email notifications: (copied from [this comment](https://github.com/sillsdev/languageforge-lexbox/issues/855#issuecomment-2149390793))

- [x] send email to users when pending project creation request has been approved
- [ ] send email to users when they have been added to existing project

Maybe take care that emails are not redundant (they don't receive two emails for the same event).

**Comment by hahn-kev** [comment]
testing:
- [ ] added to a project notification
- [ ] project approved notification
