### ISSUE TITLE
`task setup` should run `git config --local pull.ff only`

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#870]
I'd recommend running `git config --global pull.ff only`, except that it's kind of rude to change someone's Git settings without telling them. But `--local` only changes the settings in the current repository, without changing the user's personal settings. (Though we should also echo a line of output to the terminal saying "We strongly recommend running `git config --global pull.ff only`" and perhaps an explanation of why.)

The reason is so that any new devs will, by default, have their Git set up so that `git pull` will not create merge commits: merge commits on a feature branch can get quite confusing. It's better if `git pull` refuses to merge when someone else pushed commits to your branch, so that you can look at the situation and choose what to do. (Usually `git pull --rebase`, but not always, which is why I don't recommend setting `git config pull.rebase true`).

**Comment by hahn-kev** [comment]
Thanks for the idea Robin, but I don't like the idea of changing this for the user on the repo. If a user wants to make merge commits I don't have a problem with that as long as they don't make it into the main line. If they make it really difficult to follow on their feature branch I might ask them to clean it up, but enabling this setting will just add confusion, especially for people who are new to git.
