### ISSUE TITLE
Error: Unable resolve type IOpenIddictApplicationManager (dependency of OauthController)

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#871]
After rebasing my WIP branch on top of current `develop` to fix merge conflicts, I'm getting:

> Unable to resolve service for type 'OpenIddict.Abstractions.IOpenIddictApplicationManager' while attempting to activate 'LexBoxApi.Controllers.OauthController'

@hahn-kev I believe this was introduced when #847 was merged.

**Comment by hahn-kev** [comment]
It sounds like OAuth is disabled locally. Check the config? It's used in AuthKernel. 

Also why is the OAuth Controller being activated? Are you trying to use OAuth?

**Comment by rmunn** [comment]
I haven't touched the OAuthController code in my branch. AFAICT, it's being set up in AuthKernel.cs because I have

```json
    "OpenId": {
      "Enable": true
    }
```

in my `appsettings.Development.json` file. A quick `git blame` suggests that that came from #809 (specifically, [here](https://github.com/sillsdev/languageforge-lexbox/pull/809/files#diff-5d4dd1afe31a8a730a8e5f10b90b59945fc8fa5b62c866622ee411be8a9e528c)).

I've tried setting `"Enable": false`, but so far that hasn't solved the issue. So maybe I'm wrong about why the OAuthController is being activated.

There's also an optional IOpenIddictApplicationManager dependency in SeedingData, but I don't see SeedingData in the C# logs so I don't think that's what's causing it. But I'm not really certain of any of my conclusions just now.

**Comment by hahn-kev** [comment]
It's possible that there's an environment variable that's overriding that when running in k8s. Did you check that?

**Comment by hahn-kev** [comment]
Fixed.

**Comment by rmunn** [comment]
Fix working for me, thanks.
