### ISSUE TITLE
502 Bad Gateway running locally since OAuth PR merged

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#875]
Ever since #847 was merged, I've been getting 502 Bad Gateway errors when connecting to http://localhost/. Checking out the commit before #847 was merged, everything builds.

When I look at the ingress logs with `docker logs -f ingress-nginx-controller-b6c6944f4-gxwd4` I can see why the ingress controller is reporting Bad Gateway:

```
2320 upstream prematurely closed connection while reading response header from upstream, client: 192.168.65.9, server: localhost, request: "GET / HTTP/1.1", upstream: "http://10.1.8.168:3000/", host: "localhost"
```

10.1.8.168 is the current IP address of the Vite dev server (confirmed by looking at the logs for the `ui-7f8d755587-8mkvv` pod).

I have not yet been able to track down which change in #847 is causing Vite to stop responding to HTTP requests from the ingress controller, but it's definitely the commit that merged #847 (commit 55c846ee2cd11dea979fb62531cf4fde16e158c8) that's causing my issues.

P.S. This appears to be unrelated to https://github.com/sillsdev/languageforge-lexbox/issues/871, as the Bad Gateway errors are occurring both before and after the fix to https://github.com/sillsdev/languageforge-lexbox/issues/871 was pushed to `develop`.

**Comment by rmunn** [comment]
I've tried resetting the Kubernetes cluster in my local Docker Desktop, and running `docker system prune -a` to ensure there aren't any leftover container layers that somehow got corrupted; no change in behavior. Commit https://github.com/sillsdev/languageforge-lexbox/commit/55c846ee2cd11dea979fb62531cf4fde16e158c8 produces Bad Gateway, the commit before https://github.com/sillsdev/languageforge-lexbox/commit/55c846ee2cd11dea979fb62531cf4fde16e158c8 works normally.

I also updated my Docker Desktop version from 4.30.0 to 4.31.0; still no change.

@hahn-kev @myieye Can you reproduce this on Windows, or is this Linux-only behavior so far?

**Comment by hahn-kev** [comment]
I was seeing this today, but it's actually only a UI container issue. If you go to localhost/API/swagger it returns just fine. So it's purely a Svelte issue.

**Comment by megahirt** [comment]
I don't know if this is relevant, but there was a [change to the vite config](https://github.com/sillsdev/languageforge-lexbox/pull/847/files#diff-97c6e2c429ec483132c584137a18a1ade2ff6c3f4f6485f4a83db604d0323d7cL16) in #847 

I don't know why the vite config changed - couldn't find any relevant info in the PR itself

**Comment by rmunn** [comment]
Confirmed, changing `exposeServer` to false in the vite config makes the Bad Gateway errors go away.

**Comment by myieye** [comment]
I took the liberty of [reverting the vite changes](https://github.com/sillsdev/languageforge-lexbox/commit/037fb4624efdc4f339f52d1e8763df47601f703c) (that were made to get oauth to work) for now.
