### ISSUE TITLE
`new Date(string)` is dangerous, can produce unexpected results

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#876]
Open a Javascript console and type `new Date('2024-06-06')` followed by `new Date('2024/06/06')`. Would you expect those two values to produce the same result?

<details><summary>Click here for answers</summary>
<pre>
15:51:25.396 new Date('2024-06-06')
15:51:25.434 Date Thu Jun 06 2024 07:00:00 GMT+0700 (Indochina Time)
15:51:31.716 new Date('2024/06/06')
15:51:31.752 Date Thu Jun 06 2024 00:00:00 GMT+0700 (Indochina Time)
</pre>
<img src="https://github.com/sillsdev/languageforge-lexbox/assets/90762/5f71ccbf-679f-49ad-b1f4-40e811e58c34" />
</details>

Surprising, no? Note that that's on Firefox, and you might get **different** results on other browsers (Safari, for example, will probably return an invalid Date object for `'2024/06/06'`.)

Now try `new Date('2024-06-06')` vs. `new Date('2024-06-06T00:00:00')`. This time would you expect those two values to produce the same result?

<details><summary>Click here for answers</summary>
<pre>
15:56:58.944 new Date('2024-06-06')
15:56:58.979 Date Thu Jun 06 2024 07:00:00 GMT+0700 (Indochina Time)
15:57:05.023 new Date('2024-06-06T00:00:00')
15:57:05.061 Date Thu Jun 06 2024 00:00:00 GMT+0700 (Indochina Time)
</pre>
<img src="https://github.com/sillsdev/languageforge-lexbox/assets/90762/eafebfee-a406-4a10-82a0-1a19f55e4787" />
</details>

This time you should see the same results on all browsers, because this is [documented behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format) (emphasis in original):

> When the time zone offset is absent, **date-only forms are interpreted as a UTC time and date-time forms are interpreted as local time.** This is due to a historical spec error that was not consistent with ISO 8601 but could not be changed due to web compatibility. See [Broken Parser – A Web Reality Issue](https://maggiepint.com/2017/04/11/fixing-javascript-date-web-compatibility-and-reality/).

I suggested [quite some time ago](https://github.com/sillsdev/languageforge-lexbox/issues/78) using the `js-joda` library for date/time handling in Javascript. When I suggested that, I was only aware of the issue where Safari's implementation of `new Date()` is (or was, I don't know if it's changed) extremely strict where other browsers were looser in what values they accept. (E.g., other browsers allowed the time offset format `+0700` which many time libraries will generate by default when creating ISO date strings. But Safari would **only** accept `+07:00`, which caused some parts of Language Forge Classic to look wrong when viewed on Macs.)

Now that I'm aware of the issue where `new Date()` and `Date.parse()` will sometimes return surprising values, and I know that that is how the JS spec **requires** that code to behave, I'm reiterating my suggestion. We have released LexBox so it'll be harder to make the switch (we have to test that the handling of dates already in Postgres won't be broken by the change, for example), but I still think we need to make the switch: [js-joda](https://js-joda.github.io/js-joda/) for frontend code and [Nodatime](https://nodatime.org/) for backend code.

**Comment by rmunn** [comment]
If https://chrispennington.blog/blog/safari-does-not-show-new-date-from-javascript/ is to be believed, Safari doesn't support the `new Date('2024-06-06')` format, so you'll get an invalid Date object from Safari if you try to run the example code above on a Mac. @megahirt, can you confirm? If this is true, that's another reason to switch to a library that doesn't wrap native Date objects.

**Comment by hahn-kev** [comment]
Where are we using `new Date`? I don't see any of our code that is using that.

As for using a non native date object. I see the benefits, however there's also huge downsides, being that any library we interact with will expect a native date, so we'll have to convert on those edges. For example right now we can format our dates using the native date formatting built into the browser, this respects the language and we don't need to do anything to support that. If we were to use js-joda I'm not sure what we would do to format dates to display in the UI.

**Comment by rmunn** [comment]
ProjectList.svelte has `lastChange: new Date(project.lastCommit)`. Footer.svelte has `© {new Date().getFullYear()}` but that's not the same thing. There are also a couple of places in the viewer code: ActivityView.svelte has

```html
{#if row.previousTimestamp}
  <Duration totalUnits={2} start={new Date(row.timestamp)}
            end={new Date(row.previousTimestamp)}
            minUnits={DurationUnits.Second}/>
  before
{:else}
  <Duration totalUnits={2} start={new Date(row.timestamp)} minUnits={DurationUnits.Second}/>
  ago
{/if}
```

where `timestamp` and `previousTimestamp` are strings. And HistoryView.svelte in the viewer has essentially the same code.

**Comment by hahn-kev** [comment]
Ok so all those versions are using data from the server, so there's a consistent standard format being used. Maybe we should use a different method of parsing the date string, however it doesn't seem like there's a specific issue we're trying to fix unless I'm missing something?

**Comment by megahirt** [comment]
> @megahirt, can you confirm?

This blog post is 3 years old.  Running `new Date('2021-08-09')`
appears to work as expected in Safari on an up to date MacOS.

![image](https://github.com/sillsdev/languageforge-lexbox/assets/3444521/1c11fac1-c1a7-4ad3-adb1-4961480717bd)

**Comment by rmunn** [comment]
Then modern versions of Safari are more sensible in their date handling than when I encountered https://github.com/sillsdev/web-languageforge/pull/706 in 2019. Good. I'll close this as not planned.
