### ISSUE TITLE
Public projects

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#890]
From Anne in January 2024

> Sometimes there are projects that we’d like other people to be aware of and even participate with.  I assume repos are created as private, which used to be the default, but it would be good to have the option to make them public.

and in a later email

> When a repository is public, anyone can see it listed.  Probably, the only role that would need to be able to change this is the manager.  I know of at least 2 projects (Greek and English), that the managers would be happy to share.  But it would be helpful if others could see that they exist.

If we were to do this it would involve something like this:
- [ ] Give projects a visibility status: Private/null (default), public readonly, public write (it would be a bit awkward if this wasn't the same field as Confidential)
- [ ] Allow project managers to set that status on the project page
- [ ] Make a new page for all Lexbox users: Public projects.
  - All registered users can view the projects.
  - I don't know how to do the Send/Receive permissions:
    - We don't really want any random internet user to be able to register and then do a Send/Receive that deletes all the entries
    - Can everyone download the project, but only members can Upload? We don't currently support that. One way would be to block Send/Receive (already done) and provide a Download button right in the UI. e.g. with https://github.com/sillsdev/languageforge-lexbox/issues/631
    - Do you request project membership before you can Send/Receive? I think that's necessary.

**Comment by hahn-kev** [comment]
IIRC non confidential projects ARE public, that was largely the point.

**Comment by myieye** [comment]
@hahn-kev ok...yeah, that makes sense.
Now...we're talking about being able to see that a project exists. Viewing the project contents is perhaps a bit different, but...that's a question for another issue.
