### ISSUE TITLE
Unit tests sometimes fail with Npgsql.PostgresException : XX000: tuple concurrently updated

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#91]
Xunit runs tests in parallel, and this is sometimes causing test failures with the error "Npgsql.PostgresException : XX000: tuple concurrently updated". The cause of the error is https://github.com/sillsdev/languageforge-lexbox/blob/e1d22b85371e085d1b9ef9cafe69cb0ee47b7fbd/backend/Testing/Fixtures/TestingServicesFixture.cs#L38

https://www.npgsql.org/efcore/modeling/concurrency.html?tabs=data-annotations provides some background on this issue: Postgres does not like running certain commands like DROP TABLE in parallel: if two connections try to drop the same table at the same time, Postgres can end up with an internal error that doesn't have a very good error message.

The solution is probably to move the database drop-and-restore code to an Xunit [collection fixture](https://xunit.net/docs/shared-context#collection-fixture) so that it will only be run once per suite, instead of once per test class.

**Comment by hahn-kev** [comment]
Hum that's an annoying issue. 

We could certainly move it into a collection, however that could make it difficult to have custom services per test class (could be resolved though), but it would also mean that any changes to the data in db as part of the test would leak into other test classes which could get very complicated and error prone to fix/debug with lots of race conditions. 

One option would be to create a separate database (as specified on the connection string parameter) per test class, we could probably use a Generic type on the Fixture to get the test class type and therefore name so we had a consistent database name per test class, which would solve any cleanup issues and makes it easy to find the relevant data when inspecting a failure (right now you could just see the db from the last test case to run which isn't ideal).

**Comment by hahn-kev** [comment]
haven't seen this in a long time, I consider it fixed
