### ISSUE TITLE
Serialization of JWT orgs list needs to be configured, not just left to .NET defaults

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#918]
The orgs list in the JWT currently just lets .NET serialize it with its default serialization behavior, resulting an orgs list that looks like this:

```
"orgs": [
  {
    "Role": 1,
    "OrgId": "a748bd8b-6348-4980-8dee-6de8b63e4a39"
  }
]
```

But if you write code like this in Svelte:

```
$: orgsManagedByUser = user.orgs.filter(o => o.role === OrgRole.Admin).map(o => o.orgId);
```

Then it's comparing the number 1 to the string "ADMIN" and coming up false. (And it's also failing because the JSON contains o.Role rather than o.role, so the camel-case serialization convention needs to be configured here as well).

We need to tweak the serialization of the JWT in .NET to use a string rather than an int for the role in the Orgs object, and to use camel-case serialization.

**Comment by hahn-kev** [comment]
resolved this issue already here: https://github.com/sillsdev/languageforge-lexbox/pull/919
