### ISSUE TITLE
newly created projects which are added to an org don't invalidate the org gql cache

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#933]
reproduce

1. open an org page, this will cache that org in the gql cache
2. create a new project, adding it to that org
3. navigate back to the org page, the project should show up in the org list, but it does not.
4. Refresh the page which clears the cache, now the project is in the list

**Comment by rmunn** [comment]
The `addProjectToOrg` mutation is currently set to clear the GraphQL cache for the project; we should also have it clear the GQL cache for the org, or at least the org's `projects` field. Looks like we might also need to do the same for the GQL cache when a project is created with a non-null OrgId.
