### ISSUE TITLE
adding or removing a user from an org doesn't invalidate the gql cache

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#935]

**Comment by rmunn** [comment]
I believe this is fixed by #887; specifically, by commit https://github.com/sillsdev/languageforge-lexbox/pull/887/commits/bbd179d527af602081c38fe108077a3683e1a553.

**Comment by rmunn** [comment]
Confirmed by testing on localhost; now that #887 is merged, adding and removing users from orgs is updating the GQL cache correctly. Closing as completed since this was fixed by #887.
