### ISSUE TITLE
attempting to upload a reset can never finish and keeps retrying until you give up

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#944]
On staging access this project https://staging.languagedepot.org/project/smk-test-flex

download the backup of smk-flex from production, attempt to upload it to the staging project. 

Issue was on windows 11, Firefox.

**Comment by rmunn** [comment]
Could not reproduce this today; the smk-flex backup uploaded to staging just fine. Could this have been caused by a temporary network hiccup that has solved itself since then?

**Comment by hahn-kev** [comment]
Tested this out again. Here's the network tab in FF when trying to reset that project:
![image](https://github.com/user-attachments/assets/bfcdfa42-858b-49ac-bca8-4b20ddf81bf2)
unfortunately the patch which is the actual upload which looks like it fails has no recorded info in dev tools.

**Comment by myieye** [comment]
I also couldn't reproduce this in either Chrome or Firefox on Windows 11.
It took a long time, but that's all. I tried twice on Firefox.

Here are the network logs from my first run in Firefox:
![Image](https://github.com/user-attachments/assets/a39a2f04-d028-49eb-b97c-667a811c4c58)

**Comment by hahn-kev** [comment]
I just tested it out and I wasn't able to reproduce it anymore, so I guess we fixed it, yaya us!
