### ISSUE TITLE
Build desktop app

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#949]
Right now FW lite just opens a console and launches the users browser. It would be nice if we could be a little smarter about that and actually have a window with an embedded browser.

One way to do that would be with MAUI. However this doesn't work on Linux and has major issues on Mac due to a webview issue not registering keyboard events.

Looks like our solution might be to use some wrappers to build our own UI for each and inject a webview into them. See: https://devtoys.app/blog/the-journey-to-devtoys-2.0

- [x] windows
- [x] linux
- [x] #907

**Comment by megahirt** [comment]
After a bit of office discussion:
- We could shoot for a proper installer and app frame for the Windows and Mac versions.
- For the Linux version we stick with the console + browser version with no installer
