### ISSUE TITLE
let org members list other org members when adding members to a project

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#957]
Right now admins can search when adding users. We want the same thing but to list members in the org a user is in. 

This will probably require a new gql query.

**Comment by psh0078** [comment]
In the current setup, only admins can search for users to add to a project on the project page. We now want to enable organization members who are part of the project to also search for other organization members to add to the project.

**Comment by psh0078** [comment]
**Commit Message:**

Enable project member search functionality

- Implemented typeahead search for organization members when adding to a project.
- Added a dispatcher to track user ID selection from the list.
- Potential improvement: Add form clearing functionality when a user starts deleting the form.
