### ISSUE TITLE
hide member list for confidential projects

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#959]
Confidential projects should not display the list of members to users in order to protect them incase someones account is exposed. However project managers still need to see the list to be able to manage it.

This will require permission changes in `AccessProjectUsersRequirementHandler`

**Comment by rmunn** [comment]
Has this been fixed by #975? Or does it still need to be open?

**Comment by hahn-kev** [comment]
no they're unrelated. That PR was so that non members can't see members for public projects. This is for confidential projects to hide the members list, even for members.
