### ISSUE TITLE
OurWord project type auto detection doesn't work well

### ISSUE THREAD

**Issue by megahirt** [sillsdev/languageforge-lexbox#960]
In production Lexbox, the project type filter states that there is only one OurWord project.  This isn't true.  In contrast, there are several hundred unknown type projects (259 at issue creation).

How can you detect an OurWord project?  I think a pretty reliable detection would be the existence of a `.Settings` folder in the repo root

See the repo https://lexbox.org/project/guinea-bissau https://lexbox.org/hg/g/guinea-bissau/file/tip for an example.

**Comment by rmunn** [comment]
There's already code in HgService.DetermineProjectType to look for a `.Settings` folder and call it OurWord if it exists. Git blame says it was added in January 2024, so my guess is that it was added after we'd already run the DetermineProjectType for the projects we'd imported from Redmine, and if we just run DetermineProjectType again for unknown projects it will detect a lot of them as OurWord.

**Comment by hahn-kev** [comment]
Ahh I see what's wrong. The `DetermineProjectType` method only scans the files in the repo, we need to add a `directories` property to the `BrowseResponse`  class similar to the `Files` property. Then we need to update the code to check for the settings folder.
