### ISSUE TITLE
FwLite won't run on Ubuntu: ICU issues

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#974]
On Ubuntu 22.04, FwLite won't run because ICU version 72 is not found (Ubuntu 22.04 has ICU 70).

On Ubuntu 24.04, FwLite won't run because ICU can't load libdl.so. I believe that's because `icu.net.dll.config` needs to be copied to the output directory. See https://github.com/sillsdev/icu-dotnet/issues/186. I'll confirm that that's the problem, and open a PR to solve it.

**Solution** (see https://github.com/sillsdev/languageforge-lexbox/issues/974#issuecomment-2270350469 for details):

- The DLLs on Linux need symlinks named foo.72 pointing at foo.72.1.0.3.
- The LD_LIBRARY_PATH env var needs to be set to the location of the included libicu files.

**Alternate solution** implemented by #1004: Only use the included MS ICU package on Windows, and allow the system package to be used instead on Linux and OS X.

**Comment by rmunn** [comment]
This should be solvable by doing the same thing that [LfMerge.Core.csproj](https://github.com/sillsdev/LfMerge/blob/f518d8d925ae9c6fa53c856df519d425f15d27c1/src/LfMerge.Core/LfMerge.Core.csproj#L70-L73) does:

```xml
<None Include="$(Pkgicu_net)\contentFiles\any\any\icu.net.dll.config">
  <Link>icu.net.dll.config</Link>
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
```

I don't believe this is possible with an indirect package reference, because you need `GeneratePathProperty="true"` on the PackageReference in order to have the `$(Pkgicu_net)` property. So you'll need an actual package reference:

```xml
<PackageReference Include="icu.net" Version="whatever" GeneratePathProperty="true" />
```

**Comment by rmunn** [comment]
https://github.com/sillsdev/languageforge-lexbox/commit/7ac36b23e45f8a8c2857e9c2d017e82c10cbf92c fixes the libdl.so problem, but now the problem is that Ubuntu 24.04 has ICU version 74, not 72, so the following happens:

![icu-72-not-found](https://github.com/user-attachments/assets/1ed7afc2-5dae-475f-9e8e-16eed65fe6a4)

(Screenshot rather than text because I was having issues with copy-and-paste out of the VM).

Same thing happens on Ubuntu 22.04, except that it fails because the system version of ICU is 70. But either way, requiring the *specific* version of ICU to be 72 is failing on Ubuntu.

**Comment by rmunn** [comment]
Enabled trace logging to the console and found the following:

```
    icu.net: Get ICU Lib handle for icuuc, version 72
    LocalWebApp Warning: 0 : NativeLibrary.Load of .../FwLite/LocalWebApp/bin/Debug/net8.0/runtimes/linux-x64/native/libicuuc.so.72 failed with error 0
```

Turns out the file in `runtimes/linux-x64/native/` is named `libicuuc.so.72.1.0.3`. I thought at first this might be the cause of the error, that our icu.net code is looking for a file named *exactly* `libicuuc.so.72`. But copying the relevant .so files to be named exactly `lib*.so.72` didn't work:

```
cp -a libicuuc.so.72.1.0.3 libicuuc.so.72
cp -a libicui18n.so.72.1.0.3 libicui18n.so.72
cp -a libicudata.so.72.1.0.3 libicudata.so.72
```

This still gave the same "failed with error 0" message. So I'm not much further in determining why the included libicu libraries aren't loading.

**Comment by rmunn** [comment]
Made some progress. On Linux, icu.net is calling `dlopen()` with a full path to the libicuuc.so.72 file, which loads correctly. However, libicuuc.so then tries to load libicudata.so (which is a dependency of the libicuuc.so library). It's in the same directory, and on Windows, DLL files in the same directory are automatically searched. However, on Linux they are not, and you get the following:

```plaintext
find library=libicudata.so.72 [0]; searching
 search cache=/etc/ld.so.cache
 search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib		(system search path)
  trying file=/lib/x86_64-linux-gnu/libicudata.so.72
  trying file=/usr/lib/x86_64-linux-gnu/libicudata.so.72
  trying file=/lib/libicudata.so.72
  trying file=/usr/lib/libicudata.so.72
```

It's not in any of those (because the system version is ICU 70) so it fails.

However, if you set the `LD_LIBRARY_PATH` environment variable (which tells `dlopen()` where to look for dynamically-loaded libraries) to the folder where the ICU libraries are located (e.g., .../FwLite/LocalWebApp/bin/Debug/net8.0/runtimes/linux-x64/native) then the `dlopen()` call will succeed. Well, it will succeed if the library is named libicudata.so.72 instead of libicudata.72.1.0.3.

**Conclusion:**

- The DLLs on Linux need symlinks named `foo.72` pointing at `foo.72.1.0.3`.
- The LD_LIBRARY_PATH env var needs to be set to the location of the included libicu files.

**Comment by megahirt** [comment]
>Conclusion:
>
>The DLLs on Linux need symlinks named foo.72 pointing at foo.72.1.0.3.
>The LD_LIBRARY_PATH env var needs to be set to the location of the included libicu files.

So these would be linux package-related tasks, correct?
