### ISSUE TITLE
[MiniLcm] integrate SIL.WritingSystems to validate WritingSystem Ids

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#984]
MiniLcm has a struct for the WsId
https://github.com/sillsdev/languageforge-lexbox/blob/d1d4f3f4f19df24a6bc7fb044c20f4024db158b8/backend/FwLite/MiniLcm/WritingSystemId.cs#L29

we want to validate that the code is a valid lang tag we should use the `IetfLanguageTag.IsValid` function from the SIL.WritingSystems nuget package

**Comment by rmunn** [comment]
Do we want to validate in the constructor, and refuse to construct invalid WritingSystemId records? Or do we want an .IsValid method?

**Comment by hahn-kev** [comment]
no we want to refuse to construct invalid writing systems, though we may make an exception for "default" as we use that to select the default WS in some cases
