### ISSUE TITLE
AddProjectMemberInput property UsernameOrEmail should be non-nullable

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#999]
#986 changed the AddProjectMemberInput record to make UsernameOrEmail nullable. I decided not to ask for that to be changed right now as that PR was difficult to get across the finish line, but I believe we want to set UsernameOrEmail back to non-nullable, and just have the frontend code submit an empty string if there's no useful value.

**Comment by hahn-kev** [comment]
Why's that? I think the purpose is to allow the API to be called with no value, which null represents. It would feel strange to get back a validation error if you passed null when you are allowed to pass an empty string.

**Comment by rmunn** [comment]
Yeah, if empty strings are allowed then null should be allowed too. I was thinking of the concept of [making illegal states unrepresentable](https://fsharpforfunandprofit.com/posts/designing-with-types-making-illegal-states-unrepresentable/), e.g. what we really want is to be able to have the API take something like the following:

```fsharp
type AddProjectMemberInput =
    | ById of (Guid, string?)
    | ByUsernameOrEmail of string
```

But C# doesn't make that easy. So yeah, leaving UsernameOrEmail as nullable does make sense if we're going with what's simple in the C# type system. I'll close this as not planned.
